---
title: "Untitled"
author: "Michael Wu"
date: "3/29/2019"
output: html_document
---

# Data preparation

```{r power analysis all study}
source("Power analysis.R")

power.analysis(d=0.2,
               k=57,
               n1=30,
               n2=30,
               p=0.05,
               heterogeneity = "moderate")

power.analysis(d=0.1,
               k=56,
               n1=30,
               n2=30,
               p=0.05,
               heterogeneity = "moderate")


power.analysis.subgroup(TE1=0.4, 
                        TE2=0, 
                        seTE1=0.1, 
                        seTE2=0.1)
```

```{r prepare data}

# set working directory
setwd("~/Google Drive/Systematic Review/Analysis_new")

library(tidyverse) # package for tidying data
library(metafor) # package for conducting meta-analysis
library(compute.es) # package for calculating effect sizes
library(esc) # package for calculating EF from regression model
library(emmeans) # package for calculating adjusted means
# library(meta)
library(poibin)


getB <- function(x){
  return(as.numeric(unlist(x)[c(1,3,4,5)]))
  }

getgv <- function(d,v_d,n){
  J= 1- 3/ (4*n-9)
  g = J*d
  v_g = J^2 * v_d
  return(c(g, v_g))
}

# create data frame as place holders
dat <- data.frame(study = NA, author = NA, year = NA, adapted = NA, type = NA,  outcome = NA, adjusted = NA, es = NA, v = NA, lowerCI = NA, upperCI = NA)

# Peterson & Brown, 2005, <On the Use of Beta Coefficients in Meta-Analysis>
# This is for standardized beta only
B2d <- function(B,n){
  # B to r
  lamda = sign(B)
  r = B + 0.05 * lamda
  # r to d
  d = res(r = r,n = n)
  return(d)
}

```

```{r Baker 2019}

# GPA

# Interaction (Minority = 1)
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(0.315+0.003, 1.27, 564, 551,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-0.02+0.003, 1.27, 564, 551,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Asian"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(0.167+0.003, 1.27, 564, 551,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-0.114+0.003, 1.27, 564, 551,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(0.003, 1.27, 564, 551,es.type = "g"))

# Main
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,c(8:11)] <- mes(2.30, 2.32, 1.30, 1.23, 564, 541,dig = 5)[1,12:15]


# Amount of time until withdraw from class
# Main
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Baker"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Amount of time until withdraw from class"
dat[x,7] <- "No"
dat[x,c(8:11)] <- mes(67.32, 65.23, 24.98, 24.57, 564, 541,dig = 5)[1,12:15]


```

```{r Bancroft 2017}
# see Bratter 2016

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bancroft"
dat[x,3] <- "2017"
dat[x,4:11] <- NA

```

```{r Bayly 2017}
#treatment group membership was not a significant predictor for semester GPA for URM students or first-generation students

# GPA 
# Minority = URM students or first-generation
# VA+CA vs. control
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bayly"
dat[x,3] <- "2017"
dat[x,4] <- "Yes"
dat[x,5] <- "Minority subgroup-URM or First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.72,2.88,0.95,0.84,191,197,dig = 5)[1,12:15]

# VA vs. control
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bayly"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM or First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.8,2.88,0.94,0.84,198,197,dig = 5)[1,12:15]

# URM
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bayly"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.05, sqrt(((198-1) * 0.94^2 + (197-1) * 0.84^2) /(198 + 197 - 2)), 198 * (1-0.084-0.176) , 197 * (1-0.084-0.176), es.type = "g"))

# First generation
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bayly"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.02, sqrt(((198-1) * 0.94^2 + (197-1) * 0.84^2) /(198 + 197 - 2)), 198 * 0.56 ,  197 * 0.56, es.type = "g"))
  
```

```{r Binning under review}
# use longitudinal model coefficients as adjusted coefficients
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Binning"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM" # Geoff told me to assume this because of no interaction effect
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.77-0.43, sqrt((0.86^2 + 0.98^2 + 0.99^2)/3), 163/2, 163/2, es.type = "g"))

```

```{r Borman 2012}
# Table 6 Outcome is reported in standard deviations of 2012 test score, so it is technically an effect size already

# MCA Reading & Math scores

# Minority subgroup
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "MCA reading score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(0.023, 0.049^2, 401-1)
  

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "MCA math score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(0.073, 0.054^2, 403-1)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "MCA reading score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(0.055, 0.084^2, 187-1)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "MCA math score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(0.053, 0.074^2, 186-1)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "MCA reading score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(0.019, 0.039^2, 651-1)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "MCA math score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(0.104, 0.035^2, 654-1)


# Majority subgroup
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Asian"
dat[x,6] <- "MCA reading score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(-0.066, 0.050^2, 341-1)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Asian"
dat[x,6] <- "MCA math score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(-0.075, 0.046^2, 342-1)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "MCA reading score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(-0.022, 0.042^2, 667-1)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "MCA math score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(-0.005, 0.039^2, 668-1)
```

```{r Borman 2015}
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2015"
dat[x,4:11] <- NA

# Students completed up to four writing exercises during the 2011-2012 academic year.

# We expect that White and Asian American students are not threatened by academic stereotypes (and could benefit from stereotype lift) and that American Indian, African American, Hispanic, and Pacific Islander students may be subject to stereotype threat.

## Interaction
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "7th GPA"
#dat[x,7] <- "b"
#dat[x,c(8:11)] <- c(0.087, ((0.087 - 0.008)/1.96)^2, 0.008,0.166)
#
## Interaction
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "8th GPA"
#dat[x,7] <- "b"
#dat[x,c(8:11)] <- c(0.130,((0.130 - 0.028)/1.96)^2, 0.028,0.232)
#
#
## Interaction
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "9th GPA"
#dat[x,7] <- "b"
#dat[x,c(8:11)] <- c(0.179, ((0.179 - 0.004)/1.96)^2,0.004,0.354)

# GPA 

# 7th GPA calculated as d
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2015"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-URM"
#dat[x,6] <- "7th GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(0.14, 463, 463,dig = 5)[1,12:15]
#

# 8th GPA calculated as d
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2015"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-URM"
#dat[x,6] <- "8th GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(0.2, 463, 463,dig = 5)[1,12:15]
#
#
## 9th GPA calculated as d
#x<- nrow(dat[is.na(dat$author) == F,])+1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2015"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-URM"
#dat[x,6] <- "9th GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(0.3, 463, 463,dig = 5)[1,12:15]
```

```{r Borman 2016}
#x<- nrow(dat[is.na(dat$author) == F,])
#dat[x,2] <- "Borman"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "7th GPA"
#dat[x,7] <- "b"
#dat[x,c(8:11)] <- c(0.082,((0.082 - 0.008)/1.96)^2, 0.008,0.155)


# 7th GPA calculated as d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "7th GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.11, 506, 506,dig = 5)[1,12:15]


# Fall Reading test calculated as d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Fall Reading test"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0, 463, 463,dig = 5)[1,12:15]


# Fall Math test calculated as d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Fall Math test"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.09, 463, 463,dig = 5)[1,12:15]


# Spring Reading test calculated as d
x<- nrow(dat[is.na(dat$author) == F,])
dat[x,2] <- "Borman"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Spring Reading test"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.01, 463, 463,dig = 5)[1,12:15]


# Spring Math test calculated as d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Spring Math test"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.08, 463, 463,dig = 5)[1,12:15]

# Spring Language Usage test calculated as d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Spring Language Usage test"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.04, 463, 463,dig = 5)[1,12:15]
```

```{r Borman 2018}
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Borman"
#dat[x,3] <- "2018"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "7th-9th GPA"
#dat[x,7] <- "b"
#dat[x,c(8,9)] <- c(0.177, 0.057^2)


# 7th-9th GPA calculated as d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2018"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "7th-9th GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.177,1.02,920/2,920/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2018"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White and Asian"
dat[x,6] <- "7th-9th GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.036,1.02,920/2,920/2, es.type = "g"))

# simple effect
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Borman"
dat[x,3] <- "2018"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "7th-9th GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.206,1.02,324/2,324/2, es.type = "g"))
```

```{r Bowen 2013}
# It is a school with majority black

# this one follows the standardized procedure
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bowen"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Social Studies grades"
dat[x,7] <- "Yes"
dat[x,c(8:11)] <- des(0.57 / (1- 3/ (4*(58+74)-1)), 58,74 )[1,12:15]


# This compares teacher +affirmation vs. affirmation only, not the control group we want.
# need to change the risk of bias assessment here because teachers saw the essay
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Bowen"
#dat[x,3] <- "2013"
#dat[x,4] <- "Yes"
#dat[x,5] <- "Minority subgroup-Black"
#dat[x,6] <- "Social Studies grades"
#dat[x,7] <- "Yes"
#dat[x,c(8:11)] <- des(0.53 / (1- 3/ (4*(58+75)-1)), 58,75 )[1,12:15]
  

```

```{r Brady 2016 exclude, include = F}
# we are excluding lab-administered intervention

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Brady"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Hispanic"
#dat[x,6] <- "GPA"
#dat[x,7] <- "No"
#dat[x,c(8:11)] <- des(0.48, 171/2, 171/2,dig = 5)[1,12:15]
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Brady"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-White"
#dat[x,6] <- "GPA"
#dat[x,7] <- "No"
#dat[x,c(8:11)] <- des(-0.44, 171/2, 171/2,dig = 5)[1,12:15]
#
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Brady"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Hispanic"
#dat[x,6] <- "GPA"
#dat[x,7] <- "Yes"
#dat[x,c(8:11)] <- des(0.52, 171/2, 171/2,dig = 5)[1,12:15]
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Brady"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-White"
#dat[x,6] <- "GPA"
#dat[x,7] <- "Yes"
#dat[x,c(8:11)] <- des(-0.43, 171/2, 171/2,dig = 5)[1,12:15]

```

```{r Bratter 2016}
# authors gave us mean and sd

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bratter"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Semester English grades"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(2.48, sqrt(((430*0.26-1) * 11.78^2 + (456*0.25-1) * 12.46^2)/(430*0.26+456*0.25-2)),430*0.26,456*0.25, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bratter"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "STAAR Reading"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-22.34, sqrt(((430*0.26-1) * 228.73^2 + (456*0.25-1) * 248.34^2)/(430*0.26+456*0.25-2)),430*0.26,456*0.25, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bratter"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "STAAR Algebra"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-84.7, sqrt(((430*0.26-1) * 429.01^2 + (456*0.25-1) * 420.19^2)/(430*0.26+456*0.25-2)),430*0.26,456*0.25, es.type = "g"))



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bratter"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Semester English grades"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-0.28, sqrt(((430*0.63-1) * 11.78^2 + (456*0.61-1) * 12.46^2)/(430*0.63+456*0.61-2)),430*0.63,456*0.61, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bratter"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "STAAR Reading"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-21.51, sqrt(((430*0.63-1) * 228.73^2 + (456*0.61-1) * 248.34^2)/(430*0.63+456*0.61-2)),430*0.63,456*0.61, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Bratter"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "STAAR Algebra"
dat[x,7] <- "No"
dat[x,c(8:11)] <- getB(esc_B(-9.15, sqrt(((430*0.63-1) * 429.01^2 + (456*0.61-1) * 420.19^2)/(430*0.63+456*0.61-2)),430*0.63,456*0.61, es.type = "g"))



```

```{r Churchill 2018}
# main effect SA vs. control

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Churchill"
dat[x,3] <- "2018"
dat[x,4] <- "No"
dat[x,5] <- "Main" # sensation seeking is not a social identity
dat[x,6] <- "Music examination grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(62.18,60.97,5.63,5.98,35,32,dig = 5)[1,12:15]
```

```{r Cohen 2006}
# I am using the effect size calculator for this one:http://www.campbellcollaboration.org/escalc/html/EffectSizeCalculator-SMD21.php

# our examination of treatment effects focused on African American students (Experiment 1, n = 17 males, 33 females; Experiment 2, n = 34 males, 35 females) and on European American students (Experiment 1, n = 32 males, 29 females; Experiment 2, n = 36 males, 27 females). 
# detailed Majority subgroup group stats are not reported.

# we assume that treatment and control are balanced within racials and SD = 1 according to Cohen's instruction

# study 1
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 1)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "GPA in targeted course"
dat[x,7] <- "Yes"
dat[x,c(8:11)] <- getB(esc_B(.26, 1, 50, 50,es.type = "g"))

# Student race code: 0 = European American, 1 = African American
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 1)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "GPA in targeted course"
dat[x,7] <- "Yes"
dat[x,c(8:11)] <- getB(esc_B(0.29, 1, 55.5, 55.5,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 1)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "GPA in targeted course"
dat[x,7] <- "Yes"
dat[x,c(8:11)] <- getB(esc_B(0.09, 1, 55.5, 55.5,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 1)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "GPA in non-targeted course"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.31, 1, 25, 25,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 1)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "GPA in non-targeted course"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.45, 1, 55.5, 55.5,es.type = "g"))


# study 2
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 2)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "GPA in targeted course"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.34, 1, 34.5, 34.5,es.type = "g"))

# Student race code: 0 = European American, 1 = African American
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 2)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "GPA in targeted course"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.52, 1, 66, 66,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 2)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "GPA in targeted course"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.03, 1, 66, 66,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen (Study 2)"
dat[x,3] <- "2006"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "GPA in non-targeted course"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.21, 1, 34.5, 34.5,es.type = "g"))

# This is omitted because it's for both experiments combined, but there is no reporting of experiment 2 only.
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Cohen (Study 2)"
#dat[x,3] <- "2006"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "GPA in non-targeted course"
#dat[x,7] <- "d"
#dat[x,c(8,9)] <- c(0.3,(0.3/1/1.74)^2)
```

```{r Cohen 2009}
# I am using the effect size calculator for this one:http://www.campbellcollaboration.org/escalc/html/EffectSizeCalculator-SMD21.php

# we assume that treatment and control are balanced within racials and SD = 1 according to Cohen's instruction

# Black total sample: 133*0.38 + 149*0.46 + 134*0.42 = 175
# White total sample: 133*0.46 + 149*0.42 + 134*0.48 = 188

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.24, 1, 87.5, 87.5,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.07, 1, 94, 94,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.33, 1, 181.5, 181.5,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cohen"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.02, 1, 181.5, 181.5,es.type = "g"))
```

```{r Cook 2012}
# Cook study 1 uses Cohen 2009, Study 2 does not have a control group and does not report enough stats

# not enough information
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Cook (Study 1)"
dat[x,3] <- "2010"
dat[x,4:11] <- NA

```

```{r De Clercq 2019}
# No differences were found on test performance (F(2, 247) = 0.105; p = .901)

# Open-ended test composed of 5 questions and noted out of 5 points.

#In the second contrast, social belonging condition (coded 0.5) was compared to self-affirmation condition (coded -0.5), with con- trol group coded 0.

# use the original dataset

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "De Clercq"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Test score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.664,2.737,1.5642,1.5112,125,112,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "De Clercq"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Study time"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.6488,3.7821,1.09978,1.09482,84,78,dig = 5)[1,12:15]

```

```{r de Jong 2016}

# study 1
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 1)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Dutch"
dat[x,7] <- "No"
dat[x,8:11] <- mes(6.68,6.76,0.78,0.83,144,133,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 1)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "English"
dat[x,7] <- "No"
dat[x,8:11] <- mes(6.96,6.95,1.05,1.28,144,133,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 1)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Mathematics"
dat[x,7] <- "No"
dat[x,8:11] <- mes(6.55,6.63,1.12,1.01,144,133,dig = 5)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 1)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-URM"
dat[x,6] <- "Dutch"
dat[x,7] <- "No"
dat[x,8:11] <- mes(6.94,7.09,0.95,0.93,28,31,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 1)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-URM"
dat[x,6] <- "English"
dat[x,7] <- "No"
dat[x,8:11] <- mes(7,6.9,1.22,1.29,28,31,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 1)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-URM"
dat[x,6] <- "Mathematics"
dat[x,7] <- "No"
dat[x,8:11] <- mes(6.93,7.07,1.16,1.1,28,31,dig = 5)[1,12:15]


# Not really necessary to double calculate because these models controlled for other parameters not other covariates
# Estimates (controlling for effects of other parameters) can be interpreted as Cohen’s d; aGirl = 0, Boy = 1; bNative Dutch = 0, Ethnic minority = 1; cValues-affirmation = 0, Control = 1.
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 1)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-URM"
#dat[x,6] <- "Dutch"
#dat[x,7] <- "Yes"
#dat[x,8:9] <- c(-0.05, 0.26^2)
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 1)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-URM"
#dat[x,6] <- "English"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- c(0.11, 0.27^2)
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 1)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-URM"
#dat[x,6] <- "Mathematics"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- c(-0.06, 0.25^2)
#
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 1)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Dutch"
#dat[x,7] <- "Yes"
#dat[x,8:9] <- c(0.05, 0.21^2)
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 1)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "English"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- c(0.32, 0.21^2)
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 1)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Mathematics"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- c(0.04, 0.19^2)

# study 2

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "Yes"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Cito scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(530.21,530.43,11.24,11.71,88,84,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Cito scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(529.80,530.43,10.26,11.71,94,84,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "Yes"
dat[x,5] <- "Majority subgroup-URM"
dat[x,6] <- "Cito scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(530.50,531.33,11.36,8.08,6,3,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "de Jong (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-URM"
dat[x,6] <- "Cito scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(527.33,531.33,5.69,8.08,3,3,dig = 5)[1,12:15]


#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 2)"
#dat[x,3] <- "2016"
#dat[x,4] <- "Yes"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Cito scores"
#dat[x,7] <- "Yes"
#dat[x,8:9] <- c(0.15, 0.28^2)
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "de Jong (Study 2)"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Cito scores"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- c(0.28, 0.28^2)
```

```{r Dee 2015}
# check intersectionality

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.228, 10.8, 2348/2, 2348/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "No"
dat[x,8:11] <-  getB(esc_B(0.582, 10.8, 2348/2, 2348/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "No"
dat[x,8:11] <-  getB(esc_B(-0.28, 10.8, 2348/2, 2348/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "No"
dat[x,8:11] <-  getB(esc_B(-0.028, 10.8, 2348/2, 2348/2,es.type = "g"))



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "Yes"
dat[x,8:11] <-  getB(esc_B(-0.009, 10.8, 2348/2, 2348/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "Yes"
dat[x,8:11] <-  getB(esc_B(0.591, 10.8, 2348/2, 2348/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "Yes"
dat[x,8:11] <-  getB(esc_B(-0.431, 10.8, 2348/2, 2348/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Dee"
dat[x,3] <- "2015"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Final grades in the treated subject"
dat[x,7] <- "Yes"
dat[x,8:11] <-  getB(esc_B(0.063, 10.8, 2348/2, 2348/2,es.type = "g"))
```

```{r Goyer 2017}
# study 1 (Sherman 2013); 

# raw means reported in SOM

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Course Difficulty Scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.42, 93, 92,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Course Difficulty Scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(-0.11, 93, 92,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Year 1 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.22, 41, 40,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Year 2 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.22, 41, 40,dig = 5)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Course Difficulty Scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.48, 93, 92,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Course Difficulty Scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(-0.22, 93, 92,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Course Difficulty Scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.48, 93, 92,dig = 5)[1,12:15]


# study 2 Cohen 2006, 2009 ( have overlaps so no need to double count)

# not enough information
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Goyer (Study 2)"
dat[x,3] <- "2017"
dat[x,4:11] <- NA

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Goyer (Study 2)"
#dat[x,3] <- "2017"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-Hispanic"
#dat[x,6] <- "Year 1 GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(0.26, 158/2, 158/2,dig = 5)[1,12:15]
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Goyer (Study 2)"
#dat[x,3] <- "2017"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-Black"
#dat[x,6] <- "Year 2 GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(0.22, 158/2, 158/2,dig = 5)[1,12:15]

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Goyer (Study 2)"
#dat[x,3] <- "2017"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-female"
#dat[x,6] <- "Course Difficulty Scores"
#dat[x,7] <- "d"
#dat[x,8:11] <- lores(log(3.03), 0, n.1 = 177/2, n.2 = 177/2)[1,12:15]

```

```{r Gutmann 2019}
# Numbers extracted from plots using WebPlotDigitizer
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics 100 midterm exam score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(0.668485523, 0.687193764-0.668485523, 75, 0.673385301, 0.687639198-0.673385301, 73, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics 100 midterm exam score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(0.672494432, 0.691648107-0.672494432, 121, 0.71481069, 0.729064588-0.71481069, 120, es.type = "g"))



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics 212 hour exam 1 score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(0.680530973, 0.696570796-0.680530973, 143, 0.710951327, 0.720353982-0.710951327, 122, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics 212 hour exam 1 score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(0.748561947, 0.765707965-0.748561947, 366, 0.734734513, 0.743584071-0.734734513, 381, es.type = "g"))


# using effect size calculator from frequency table to d
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics 100 final grades"
dat[x,7] <- "No"
dat[x,8:9] <- getgv(-0.2212, 0.0273, 75+73)
#dat[x,8:11] <- c(-0.2212, 0.0273, -0.5449, 0.1024)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics 100 final grades"
dat[x,7] <- "No"
dat[x,8:9] <- getgv(-0.328, 0.0162, 121+120)
#dat[x,8:9] <- c(-0.328, 0.0162, -0.5772, -0.0789)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics 212 final grades"
dat[x,7] <- "No"
dat[x,8:9] <- getgv(-0.1159, 0.0152, 143+122)
#dat[x,8:9] <- c(-0.1159, 0.0152, -0.3579, 0.1261)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Gutmann"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics 212 final grades"
dat[x,7] <- "No"
dat[x,8:9] <- getgv(0.0852, 0.0054, 366+381)
#dat[x,8:9] <- c(0.0852, 0.0054, -0.0584, 0.2289)
```

```{r Hadden 2019}
# I am using effect size calculator for this one: http://www.campbellcollaboration.org/escalc/html/EffectSizeCalculator-SMD8.php
# Non-FSM: 210;224;434 (control, affirmation, all)
# FSM: 59;69;128 (control, affirmation, all)

# 
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hadden"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-FSM"
dat[x,6] <- "GCSE Mathematics"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(-0.084,(-0.084+0.303)/1.96,69,-0.438,(-0.438+0.588)/1.96,59,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hadden"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-nonFSM"
dat[x,6] <- "GCSE Mathematics"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(0.088,(0.088+0.039)/1.96,224,0.048,(0.048+0.073)/1.96,210,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hadden"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-FSM"
dat[x,6] <- "GCSE Mathematics"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_mean_se(-0.099,(-0.099+0.280)/1.96,69,-0.478,(-0.478+0.645)/1.96,59,es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hadden"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-nonFSM"
dat[x,6] <- "GCSE Mathematics"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_mean_se(0.1,(0.1+0.037)/1.96,224,0.049,(0.049+0.071)/1.96,210,es.type = "g"))
```

```{r Hanselman 2014}
# multilevel model with different covariates
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.068,0.68,310/2,310/2,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.012,0.68,600/2,600/2,es.type = "g"))


```

```{r Hanselman 2016 2017}

# cohort 1

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "7th GPA"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(0.062,	0.057^2, 331)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "8th GPA"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(0.152,	0.07^2, 331)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Mathematcis, Grade 7"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(0.072,	0.059^2, 331)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Mathematcis, Grade 8"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(0.101,	0.07^2, 331)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Reading, Grade 7"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.034,	0.069^2, 331)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 1)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Reading, Grade 8"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.03,	0.071^2, 331)

# study 2
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 2)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "7th GPA"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.002, 0.042^2, 449)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 2)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "8th GPA"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.072, 0.058^2, 449)


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 2)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Mathematcis, Grade 7"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.085,	0.047^2, 449)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 2)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Mathematcis, Grade 8"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.08,	0.044^2, 449)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 2)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Reading, Grade 7"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.005,	0.055^2, 449)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hanselman (Study 2)"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "WKCE Reading, Grade 8"
dat[x,7] <- "Yes"
dat[x,c(8,9)] <- getgv(-0.005,	0.056^2, 449)


```

```{r Harackiewicz 2014}

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Continuing generation"
dat[x,6] <- "Biology Course Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.82,2.86,0.69,0.69,325,319,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Continuing generation"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.17,3.2,0.62,0.63,325,319,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Continuing generation"
dat[x,6] <- "Continuation"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_bin_prop(0.748,325,0.777,319, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "Biology Course Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.62,2.38,0.78,0.85,77,77,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.05,2.81,0.64,0.81,77,77,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "Continuation"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_bin_prop(0.857,77,0.662,77, es.type = "g"))




x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-First generation"
dat[x,6] <- "Biology Course Grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_beta(0.09, 0.73, 325+77, 319+77, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_beta(0.1, 0.65, 325+77, 319+77, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-First generation"
dat[x,6] <- "Continuation"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_chisq(8.8, 0.01, 798, es.type = "g"))
```

```{r Harackiewicz 2016}
# ignoring the UV condition
#URM = Underrepresented Minority (URM = +1, Majority = −1), FG = First-generation (FG = +1, Continuing-generation = −1). VA = Values Affirmation (VA = +1, Control = −1).

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Biology course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(2*(-0.01) + 2*(-0.02), 0.81, 1040/4, 1040/4, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White and Asian"
dat[x,6] <- "Biology course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(2*(-0.01) - 2*(-0.02), 0.81, 1040/4, 1040/4, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-First generation"
dat[x,6] <- "Biology course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(2*(-0.01) + 2*(-0.05), 0.81, 1040/4, 1040/4, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Harackiewicz"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Continuing generation"
dat[x,6] <- "Biology course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(2*(-0.01) - 2*(-0.05), 0.81, 1040/4, 1040/4, es.type = "g"))
```

```{r Hayes 2019}
# Study 1: Middle school students

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hayes (Study 1)"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic" # almost entire sample is Latino
dat[x,6] <- "Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(84.21,85.77,4.97,5.45,116/3,116/3,dig = 5)[1,12:15] # there are three conditions, one of which is not relevant


# Study 2: College students
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Hayes (Study 2)"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation" # only 1st year student in the sample
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(2.86,0.1,39,2.93,0.1,39,es.type = "g"))

```

```{r Jordt 2017}
# We did not include Asian-American students and interna- tional students in our analyses (38.7% and 5.9% of the overall sample, respectively).
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Jordt"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "Exam grades"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-8.1+6.45, 278.3 * 0.042*2, 963, 970, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Jordt"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Male"
dat[x,6] <- "Exam grades"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(6.45, 278.3 * 0.042*2, 963, 970, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Jordt"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-URM"
dat[x,6] <- "Exam grades"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(10.29+6.45, 278.3 * 0.042*2, 963, 970, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Jordt"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Exam grades"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(6.45, 278.3 * 0.042*2, 963, 970, es.type = "g"))
```

```{r Kim 2019}
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kim"
dat[x,3] <- "2019"
dat[x,4] <- "Yes"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- fes(3.24, 110, 110,dig = 5)[1,12:15]
```

```{r Kinias 2016}
# they combined two conditions into the control group

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kinias (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "MBA core course grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.109,3.205,0.688,0.694,266/2,266/2,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kinias (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "MBA core course grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.948,2.739,0.654,0.763,130/2,130/2,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kinias (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "MBA core course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(2*0.028 + 2*0.076, sqrt(( (198-1) * 0.694^2 + (198-1) * 0.763^2 ) / (198 + 198 - 2)), 198, 198, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kinias (Study 2)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Male"
dat[x,6] <- "MBA core course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(2*0.028 - 2*0.076, sqrt(( (198-1) * 0.694^2 + (198-1) * 0.763^2 ) / (198 + 198 - 2)), 198, 198, es.type = "g"))
```

```{r Kost-Smith 2010}
# The analysis in the main text same as Miyake 2010
kost <- haven::read_dta("Kost-smith.dta")
#kost2010 <- kost[kost$Cohort == "Spring 2010",]

#table(kost2010$FEMALE, kost2010$AFFIRM)
#
#fit <- lm(COURSE_GRADE ~ as.factor(FEMALE) * as.factor(AFFIRM) + MATH, #kost2010)
#emmeans(fit, "AFFIRM", "FEMALE")
#
#fit <- lm(COURSE_SCORE ~ as.factor(FEMALE) * as.factor(AFFIRM) + MATH, #kost2010)
#emmeans(fit, "AFFIRM", "FEMALE")
#
#fit <- lm(RAW_ALL_EXAMS ~ as.factor(FEMALE) * as.factor(AFFIRM) + MATH, #kost2010)
#emmeans(fit, "AFFIRM", "FEMALE")
#
## physics course grade
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Kost-Smith"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-Female"
#dat[x,6] <- "Physics course grade"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_mean_se(2.62, 0.0946, 68, 2.36, 0.1073, 54, #es.type = "g"))
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Kost-Smith"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Majority subgroup-Male"
#dat[x,6] <- "Physics course grade"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_mean_se(2.64, 0.0546, 203, 2.64, 0.0664, 139, #es.type = "g"))
#
## physics course score
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Kost-Smith"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-Female"
#dat[x,6] <- "Physics course score"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_mean_se(70.2, 1.472, 68, 66.5, 1.652, 54, es.type #= "g"))
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Kost-Smith"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Majority subgroup-Male"
#dat[x,6] <- "Physics course score"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_mean_se(71.1, 0.849,203, 70.6, 1.029, 139, es.type #= "g"))
#
## Physics exam score
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Kost-Smith"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-Female"
#dat[x,6] <- "Physics course score"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_mean_se(65.3, 1.452, 68, 62.4, 1.630, 54, es.type #= "g"))
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Kost-Smith"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Majority subgroup-Male"
#dat[x,6] <- "Physics course score"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_mean_se(67.8, 0.837,203, 68.1, 1.018, 139, es.type #= "g"))


# using Miyake 2010 to get pooled SD (FMCE score is not in the dataset I have)
sd_ks <- sqrt(((137-1) * 26.3^2 + (55-1) * 30.6^2 + (75-1) * 27.3^2 + (41-1) * 25.1^2) /(137 + 55 + 75 + 41 - 4))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "FMCE grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(12.9-0.6, sd_ks, 55,41, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Male"
dat[x,6] <- "FMCE grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.6, sd_ks, 137,75, es.type = "g"))

```

```{r Kost-Smith 2012}

kost2012 <- kost[kost$Cohort == "Spring 2011",]

table(kost2012$FEMALE, kost2012$AFFIRM)

temp <- kost2012 %>% group_by(FEMALE, AFFIRM) %>% summarise(
  m_course_grade = mean(COURSE_GRADE, na.rm = T),
  sd_course_grade = sd(COURSE_GRADE, na.rm = T),
  m_course_score = mean(COURSE_SCORE, na.rm = T),
  sd_course_score = sd(COURSE_SCORE, na.rm = T),
  m_exam_score = mean(RAW_ALL_EXAMS, na.rm = T),
  sd_exam_score = sd(RAW_ALL_EXAMS, na.rm = T)
)


## unadjusted

# physics course grade
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics course grade"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp[4,3], temp[4,4], 89, temp[3,3], temp[3,4], 60, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics course grade"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp[2,3], temp[2,4], 232, temp[1,3], temp[1,4], 150, es.type = "g"))

# physics course score
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics course score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp[4,5], temp[4,6], 89, temp[3,5], temp[3,6], 60, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics course score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp[2,5], temp[2,6], 232, temp[1,5], temp[1,6], 150, es.type = "g"))

# Physics exam score

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics exam score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp[4,7], temp[4,8], 89, temp[3,7], temp[3,8], 60, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics exam score"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp[2,7], temp[2,8], 232, temp[1,7], temp[1,8], 150, es.type = "g"))


# adjusted

# COURSE_GRADE
kost2012$AFFIRM <- ifelse(kost2012$AFFIRM == 1, "Affirm", "Control")
kost2012$FEMALE <- ifelse(kost2012$FEMALE == 1, "Female", "Male")

fit <- lm(COURSE_GRADE ~ as.factor(FEMALE) * as.factor(AFFIRM) + MATH, kost2012)
fit.emm <- emmeans(fit, "AFFIRM", "FEMALE")
temp <- as.data.frame(eff_size(fit.emm, sigma = sigma(fit), edf = 526))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics course grade"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[1,3], (temp[1,4])^2, 531)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics course grade"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[2,3], (temp[2,4])^2, 531)
  
# COURSE_SCORE
fit <- lm(COURSE_SCORE ~ as.factor(FEMALE) * as.factor(AFFIRM) + MATH, kost2012)
fit.emm <- emmeans(fit, "AFFIRM", "FEMALE")
temp <- as.data.frame(eff_size(fit.emm, sigma = sigma(fit), edf = 526))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics course score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[1,3], (temp[1,4])^2, 531)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics course score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[2,3], (temp[2,4])^2, 531)

#RAW_ALL_EXAMS
fit <- lm(RAW_ALL_EXAMS ~ as.factor(FEMALE) * as.factor(AFFIRM) + MATH, kost2012)
fit.emm <- emmeans(fit, "AFFIRM", "FEMALE")
temp <- as.data.frame(eff_size(fit.emm, sigma = sigma(fit), edf = 526))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics exam score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[1,3], (temp[1,4])^2, 531)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Kost-Smith"
dat[x,3] <- "2012"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics exam score"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[2,3], (temp[2,4])^2, 531)

```

```{r Lauer 2013}

# treat learning gains as adjusted coefficient
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Introductory biology learning gains"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.07,sqrt(((131-1) * 15.1^2 + (138-1) * 14.4^2) /(131 + 138 - 2)), 132/2,132/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Biochemistry learning gains"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.06,sqrt(((122-1) * 8.8^2 + (97-1) * 12.7^2) /(122 + 97 - 2)), 185/2,185/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Physics 1 learning gains"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.25,sqrt(((13-1) * 10.8^2 + (52-1) * 20.7^2) /(13 + 52 - 2)), 44/2,44/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Physics 2 learning gains"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.04,sqrt(((15-1) * 11.1^2 + (111-1) * 15.5^2) /(15 + 111 - 2)), 89/2,89/2, es.type = "g"))



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Introductory biology learning gains"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(-1.7,sqrt(((131-1) * 15.1^2 + (138-1) * 14.4^2) /(131 + 138 - 2)), 260/2,260/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Biochemistry learning gains"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(-1.5,sqrt(((122-1) * 8.8^2 + (97-1) * 12.7^2) /(122 + 97 - 2)), 212/2,12/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Physics 1 learning gains"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(3.96,sqrt(((13-1) * 10.8^2 + (52-1) * 20.7^2) /(13 + 52 - 2)), 65/2,65/2, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lauer"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Physics 2 learning gains"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(-5.44,sqrt(((15-1) * 11.1^2 + (111-1) * 15.5^2) /(15 + 111 - 2)), 124/2,124/2, es.type = "g"))




#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Lauer"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Introductory biology fall course grades"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(74.3,73.7,15.1,14.4,131,138)[1,12:15]
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Lauer"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Biochemistry fall course grades"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(80,77.4,8.8,12.7,122,97)[1,12:15]
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Lauer"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Physics 1 fall course grades"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(83.2,78.8,10.8,20.7,13,52)[1,12:15]
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Lauer"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "Physics 2 fall course grades"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(82.9,80.2,11.1,15.5,15,111)[1,12:15]


```

```{r Layous 2016 exclude, include = F}
# we are excluding lab-administered intervention

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Layous"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Main"
#dat[x,6] <- "S1 GPA"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(3.16,2.96,0.58,0.71,46,56)[1,12:15]
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Layous"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Main"
#dat[x,6] <- "S2 GPA"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(3.21,2.81,0.68,0.8,41,46)[1,12:15]


#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Layous"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(0.72, 41, 46)[1,12:15]

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Layous"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Female"
#dat[x,6] <- "GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_B(0.17-0.5*0.25, 0.17/0.49, 41, 46,es.type = "g"))

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Layous"
#dat[x,3] <- "2016"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Male"
#dat[x,6] <- "GPA"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- getB(esc_B(0.17+0.5*0.25, 0.25/0.72, 41, 46,es.type = "g"))
```

```{r Lokhande 2019}
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(5.23,4.86,3.34,3.46,374,294)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(6.02,5.42,3.66,3.54,374,294)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.2, 294*0.488,374*0.488)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(-0.05, 294*(1-0.488),374*(1-0.488))[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Turkish"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.33, 294*0.198,374*0.198)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Arabic"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.24, 294*0.135,374*0.135)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Eastern European"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(-0.07, 294*0.174,374*0.174)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.63-0.55,3.39,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Turkish"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(1.2-0.55,3.39,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Arabic"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.75-0.55,3.39,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Eastern European"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.08-0.55,3.39,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Wave 1 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.55,3.39,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.18, 294*0.488,374*0.488)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.18, 294*(1-0.488),374*(1-0.488))[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Turkish"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.35, 294*0.198,374*0.198)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Arabic"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.35, 294*0.135,374*0.135)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Eastern European"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- des(0.2, 294*0.174,374*0.174)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Female"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.27-0.14,3.61,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Turkish"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.97-0.14,3.61,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Arabic"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.78-0.14,3.61,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Eastern European"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.65-0.14,3.61,374,294,es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Lokhande"
dat[x,3] <- "2019"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "Wave 2 Math scores"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.14,3.61,374,294,es.type = "g"))
```

```{r Miyake 2010}

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Biology mean exam score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(69.4,72.7,13.2,12.5,178,105,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Biology mean exam score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(65.2,62.7,13.8,11.9,69,47,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Biology final exam score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(70.4,73.3,14.2,12.8,178,105,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Biology final exam score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(66.7,61.3,15.6,13.6,69,47,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Biology final course grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(73.9,76.0,10.8,10.5,178,105,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Biology final course grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(70.5,69.3,12.1,9.9,69,47,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "End-of-semester FMCE"
dat[x,7] <- "No"
dat[x,8:11] <- mes(72.7,74.7,26.3,27.3,137,75,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "End-of-semester FMCE"
dat[x,7] <- "No"
dat[x,8:11] <- mes(63.6,56.2,30.6,25.1,55,41,dig = 5)[1,12:15]


#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Miyake"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Majority subgroup-Male"
#dat[x,6] <- "Beginning-of-semester FMCE"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(39.1,41.5,27.9,29.7,137,75,dig = 5)[1,12:15]

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Miyake"
#dat[x,3] <- "2010"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup-Female"
#dat[x,6] <- "Beginning-of-semester FMCE"
#dat[x,7] <- "No"
#dat[x,8:11] <- mes(25.9,23.7,18.0,13.4,55,41,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Biology final exam score"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(70.4,73.2,12.9,12.8,178,105,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Biology final exam score"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(68.5,60.2,14.9,14.7,69,47,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Biology final course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(73.7,75.7,9.7,9.7,178,105,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Miyake"
dat[x,3] <- "2010"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Biology final course grade"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(72.3,68.2,11.2,11.1,69,47,dig = 5)[1,12:15]


```

```{r Peters 2017}

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Peters"
dat[x,3] <- "2017"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Final grades"
dat[x,7] <- "No"
dat[x,8:11] <- mes(80.03,80.03,13.55,12.92,221/2,221/2,dig = 5)[1,12:15]

```

```{r Powers 2016}
# uses Cohen 2006 & 2009 and Cook 2012
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Powers (Study 1)"
dat[x,3] <- "2016"
dat[x,4:11] <- NA

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Powers (Study 2)"
dat[x,3] <- "2016"
dat[x,4:11] <- NA

```

```{r Protzko 2016}

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Protzko"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White and Asian"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.316,3.262,0.586,0.603,124/2,124/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Protzko"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(1.991,2.051,1.022,1.073,119/2,119/2,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Protzko"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Black and Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.07-0.001, sqrt(( (152-1) * 1.043 ^2 + (223-1) * 0.593 ^2  ) / (328-33+134-54-2)), (328-33+134-54)/2, (328-33+134-54)/2, es.type = "g"))

# (134-54)* 0.94 + (328-33) * 0.26; 152
# (134-54)* (1-0.94) + (328-33) * (1-0.26);223

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Protzko"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(-0.001, sqrt(( (152-1) * 1.043 ^2 + (223-1) * 0.593 ^2  ) / (328-33+134-54-2)), (328-33+134-54)/2, (328-33+134-54)/2, es.type = "g"))
```

```{r Purdie-Greenaway under review}
# use their original data (Study 2)

purdie <- haven::read_sav("Purdie-Greenaway.sav")
purdie <- purdie[is.na(purdie$Condition) == F,] # 74 in affirmation & control
purdie$Condition <- ifelse(purdie$Condition == 1, "Affirm", "Control")
purdie$Gender <- ifelse(purdie$Gender == 1, "Female", "Male")
purdie$Race <- ifelse(purdie$Race == 1, "White", "URM")

# unadjusted
table(purdie$Gender, purdie$Condition)
table(purdie$Race, purdie$Condition)

temp1 <- purdie %>% group_by(Gender, Condition) %>% summarise(
  m = mean(gpaq4sixth, na.rm = T),
  sd = sd(gpaq4sixth, na.rm = T)
)

temp2 <- purdie %>% group_by(Race, Condition) %>% summarise(
  m = mean(gpaq4sixth, na.rm = T),
  sd = sd(gpaq4sixth, na.rm = T)
)


## unadjusted

# gender
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp1[1,3], temp1[1,4], 21, temp1[2,3], temp1[2,4], 19, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp1[3,3], temp1[3,4], 17, temp1[4,3], temp1[4,4], 17, es.type = "g"))

# race
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp2[1,3], temp2[1,4], 26, temp2[2,3], temp2[2,4], 26, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_sd(temp2[3,3], temp2[3,4], 12, temp2[4,3], temp2[4,4], 10, es.type = "g"))

# adjusted

# gender

fit <- lm(gpaq4sixth ~ as.factor(Gender) * as.factor(Condition) + Race + CMTPRELEVELMN + gpaq12sixth, purdie)
fit.emm <- emmeans(fit, "Condition", "Gender")
temp <- as.data.frame(eff_size(fit.emm, sigma = sigma(fit), edf = 67))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[1,3], (temp[1,4])^2, 74)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[2,3], (temp[2,4])^2, 74)


# race


fit <- lm(gpaq4sixth ~ as.factor(Race) * as.factor(Condition) + Gender +CMTPRELEVELMN + gpaq12sixth, purdie)
fit.emm <- emmeans(fit, "Condition", "Race")
temp <- as.data.frame(eff_size(fit.emm, sigma = sigma(fit), edf = 67))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[1,3], (temp[1,4])^2, 74)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Purdie-Greenaway"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:9] <- getgv(temp[2,3], (temp[2,4])^2, 74)


#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Purdie-Greenaway"
#dat[x,3] <- "under review"
#dat[x,4] <- "No"
#dat[x,5] <- "Main"
#dat[x,6] <- "Quarter 4 Grades"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(2*sqrt(0.067/(1-0.067)), 109/2, 109/2)[1,12:15] # f^2 = #etasquared/(1-etasquared), d=2f, Cohen (1988) page. 257
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Purdie-Greenaway"
#dat[x,3] <- "under review"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction-Black and Hispanic"
#dat[x,6] <- "Quarter 4 Grades"
#dat[x,7] <- "Yes"
#dat[x,8:11] <- des(2*sqrt(0.001/(1-0.001)), 109/2, 109/2)[1,12:15]


```

```{r Rapa 2016}
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Rapa"
dat[x,3] <- "2016"
dat[x,4] <- "Yes"
dat[x,5] <- "Main"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.64,3.33,0.51,0.63,25,28,dig = 5)[1,12:15]

```

```{r Rozek 2015}
# no new evidence beyond Hanselman, 2014

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Rozek"
dat[x,3] <- "2015"
dat[x,4:11] <- NA
```

```{r Schwalbe 2018}
# Study 6
# Pass rate
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Main"
dat[x,6] <- "Pass rates"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.042, 0.4, 2719, 1744, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Functional skills"
dat[x,6] <- "Pass rates"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.041, 0.4, 2719*0.431, 1744*0.426, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Black Caribbeans"
dat[x,6] <- "Pass rates"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.07, 0.4, 2719*0.027, 1744*0.028, es.type = "g"))



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Main"
dat[x,6] <- "Pass rates"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.041, 0.4, 2719, 1744, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Functional skills"
dat[x,6] <- "Pass rates"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.038, 0.4, 2719*0.431, 1744*0.426, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Black Caribbeans"
dat[x,6] <- "Pass rates"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.071, 0.4, 2719*0.027, 1744*0.028, es.type = "g"))



# Attendance

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Main"
dat[x,6] <- "Attendance"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.023, 0.39, 2459, 2042, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Functional skills"
dat[x,6] <- "Attendance"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.044, 0.39, 2459*0.431, 2042*0.426, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Black Caribbeans"
dat[x,6] <- "Attendance"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_B(0.160, 0.39, 2459*0.027, 2042*0.028, es.type = "g"))



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Main"
dat[x,6] <- "Attendance"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.018, 0.39, 2459, 2042, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Functional skills"
dat[x,6] <- "Attendance"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.047, 0.39, 2459*0.431, 2042*0.426, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Schwalbe"
dat[x,3] <- "2018"
dat[x,4] <- "Yes" # affirming text message
dat[x,5] <- "Minority subgroup-Black Caribbeans"
dat[x,6] <- "Attendance"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_B(0.188, 0.39, 2459*0.027, 2042*0.028, es.type = "g"))


```

```{r Serra-Garcia under review}
# Study 1 (reanalysis of Miyake et al., 2010, drop)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 1)"
dat[x,3] <- "under review"
dat[x,4:11] <- NA

# x<- nrow(dat[is.na(dat$author) == F,]) +1
# dat[x,2] <- "Serra-Garcia (Study 1)"
# dat[x,3] <- "under review"
# dat[x,4] <- "No"
# dat[x,5] <- "Interaction-Female"
# dat[x,6] <- "Biology final exam score"
# dat[x,7] <- "No"
# dat[x,8:11] <- getB(esc_B(0.432-0.246, sqrt(( (178-1) * 14.2^2 + (105-1) * 12.8^2 # + (69-1) * 15.6^2 + (47-1) * 13.6^2 ) / (178 + 105 + 69 + 47 - 4)), 247, 152, # es.type = "g"))
# 
# x<- nrow(dat[is.na(dat$author) == F,]) +1
# dat[x,2] <- "Serra-Garcia (Study 1)"
# dat[x,3] <- "under review"
# dat[x,4] <- "No"
# dat[x,5] <- "Interaction-Male"
# dat[x,6] <- "Biology final exam score"
# dat[x,7] <- "No"
# dat[x,8:11] <- getB(esc_B(-0.246, sqrt(( (178-1) * 14.2^2 + (105-1) * 12.8^2 + # (69-1) * 15.6^2 + (47-1) * 13.6^2 ) / (178 + 105 + 69 + 47 - 4)), 247, 152, # es.type = "g"))
# 
# x<- nrow(dat[is.na(dat$author) == F,]) +1
# dat[x,2] <- "Serra-Garcia (Study 1)"
# dat[x,3] <- "under review"
# dat[x,4] <- "No"
# dat[x,5] <- "Interaction-Female"
# dat[x,6] <- "Biology final course grade"
# dat[x,7] <- "No"
# dat[x,8:11] <- getB(esc_B(0.299-0.191, sqrt( ( (178-1) * 10.8^2 + (105-1) * # 10.5^2 + (69-1) * 12.1^2 + (47-1) * 9.9^2  ) / (178 + 105 + 69 + 47 - 4) ) , 247, # 152, es.type = "g"))
# 
# x<- nrow(dat[is.na(dat$author) == F,]) +1
# dat[x,2] <- "Serra-Garcia (Study 1)"
# dat[x,3] <- "under review"
# dat[x,4] <- "No"
# dat[x,5] <- "Interaction-Male"
# dat[x,6] <- "Biology final course grade"
# dat[x,7] <- "No"
# dat[x,8:11] <- getB(esc_B(-0.191, sqrt( ( (178-1) * 10.8^2 + (105-1) * 10.5^2 + # (69-1) * 12.1^2 + (47-1) * 9.9^2  ) / (178 + 105 + 69 + 47 - 4) ) , 192, 116, # es.type = "g"))
# 
# 
# x<- nrow(dat[is.na(dat$author) == F,]) +1
# dat[x,2] <- "Serra-Garcia (Study 1)"
# dat[x,3] <- "under review"
# dat[x,4] <- "No"
# dat[x,5] <- "Interaction-Female"
# dat[x,6] <- "Biology final course grade"
# dat[x,7] <- "No"
# dat[x,8:11] <- getB(esc_B(0.343-0.075, sqrt( ( (178-1) * 10.8^2 + (105-1) * # 10.5^2 + (69-1) * 12.1^2 + (47-1) * 9.9^2  ) / (178 + 105 + 69 + 47 - 4) ) , 192, # 116, es.type = "g"))
# 
# x<- nrow(dat[is.na(dat$author) == F,]) +1
# dat[x,2] <- "Serra-Garcia (Study 1)"
# dat[x,3] <- "under review"
# dat[x,4] <- "No"
# dat[x,5] <- "Interaction-Male"
# dat[x,6] <- "Biology final course grade"
# dat[x,7] <- "No"
# dat[x,8:11] <- getB(esc_B(-0.075, sqrt( ( (178-1) * 10.8^2 + (105-1) * 10.5^2 + # (69-1) * 12.1^2 + (47-1) * 9.9^2  ) / (178 + 105 + 69 + 47 - 4) ) , 192, 116, # es.type = "g"))


# Study 2 (a repliaction study)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 2)"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics quiz grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(66.95299,63.25759,16.23619,16.39845,39,22,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 2)"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics final exam score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(69.38462,75.27273,19.58331,21.20238,39,22,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 2)"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Physics final grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(68.53846,68.63636,15.03128,14.8566,39,22,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 2)"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics quiz grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(70.71377,76.64394,15.95548,12.67724,46,22,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 2)"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics final exam score"
dat[x,7] <- "No"
dat[x,8:11] <- mes(78.41304,73.40909,16.42299,18.50266,46,22,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Serra-Garcia (Study 2)"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Physics final grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(73.84783,75.68182,14.1625,12.16312,46,22,dig = 5)[1,12:15]


```

```{r Sherman 2013}

## Study 1

# SE = SD/sqrt(N)
# mes(2.62, 2.40, 0.06 * sqrt(41), 0.06*sqrt(40), 41,40)

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Year 1 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(2.62,0.06,41,2.4,0.06,40, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "Year 1 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(3.4,0.05,51,3.44,0.05,52, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Year 2 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(2.09,0.09,41,1.7,0.09,40, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "Year 2 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(3.11,0.08,51,3.09,0.08,52, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Year 3 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(1.92,0.1,41,1.67,0.11,40, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "Year 3 GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(3.12,0.1,51,3.27,0.09,52, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Year 1 GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.29,92,92, dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Year 2 GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.43,92,92, dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 1)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "Year 3 GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.24,92,92, dig = 5)[1,12:15]



# Study 2

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 2)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(2.84,0.12,26,2.46,0.11,29, es.type = "g"))


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 2)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- getB(esc_mean_se(3.58,0.09,46,3.69,0.09,50, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 2)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Hispanic"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.45,75.5,75.5, dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Sherman (Study 2)"
dat[x,3] <- "2013"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-White"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.13,75.5,75.5, dig = 5)[1,12:15]
```

```{r Shnabel 2013}
# uses Cohen 2006 & 2009
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Shnabel (Study 1)"
dat[x,3] <- "2013"
dat[x,4:11] <- NA

# Shnabel 2013 (Study 1)

#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Shnabel (Study 1)"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Interaction"
#dat[x,6] <- "GPA"
#dat[x,7] <- "d"
#dat[x,8:11] <- fes(16.05, 344/2,344/2,dig = 5)[1,12:15]
#
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Shnabel (Study 1)"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Minority subgroup"
#dat[x,6] <- "GPA"
#dat[x,7] <- "d"
#dat[x,8:11] <- fes(18.13, 344/2,344/2,dig = 5)[1,12:15]
#
#x<- nrow(dat[is.na(dat$author) == F,]) +1
#dat[x,2] <- "Shnabel (Study 1)"
#dat[x,3] <- "2013"
#dat[x,4] <- "No"
#dat[x,5] <- "Majority subgroup"
#dat[x,6] <- "GPA"
#dat[x,7] <- "d"
#dat[x,8:11] <- fes(1.84, 344/2,344/2,dig = 5)[1,12:15]
```

```{r Silverman 2014}
# Study 2
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Silverman (Study 2)"
dat[x,3] <- "2014"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Blind"
dat[x,6] <- "Instructor-graded student progress"
dat[x,7] <- "Yes"
dat[x,8:11] <- des(0.64,35/2,35/2, dig = 5)[1,12:15]
```

```{r Tibbetts 2016 2017}
# Study 1a

# semester grade
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "S1 Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.11,3.07,0.5,0.52,72,69,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "S2 Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.15,2.99,0.6,0.74,72,69,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "S3 Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.27,3.04,0.53,0.7,72,69,dig = 5)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-First generation"
dat[x,6] <- "S1 Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.21,3.24,0.58,0.5,304,304,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-First generation"
dat[x,6] <- "S2 Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.27,3.28,0.64,0.59,304,304,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-First generation"
dat[x,6] <- "S3 Semester Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.35,3.37,0.56,0.56,304,304,dig = 5)[1,12:15]



# GPA
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.16,2.98,0.58,0.7,76,74,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Continuing generation"
dat[x,6] <- "GPA"
dat[x,7] <- "No"
dat[x,8:11] <- mes(3.25,3.28,0.57,0.49,323,315,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-First generation"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_beta(0.09+0.08, sqrt(((399-1) * 0.54 ^2 + (389-1) * 0.65 ^2) / (399 + 389- 2)), 399, 389, es.type = "g"))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1a)"
dat[x,3] <- "2016"
dat[x,4] <- "No"
dat[x,5] <- "Interaction-Continuing generation"
dat[x,6] <- "GPA"
dat[x,7] <- "Yes"
dat[x,8:11] <- getB(esc_beta(0.08, sqrt(((399-1) * 0.54 ^2 + (389-1) * 0.65 ^2) / (399 + 389- 2)), 399, 389, es.type = "g"))
```

```{r Tibbetts 2018}
# Study 1b

# independent & interdependent combined
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1b)"
dat[x,3] <- "2018"
dat[x,4] <- "Yes"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "Course Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.52,2.33,1,1.24,438/2,438/4,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1b)"
dat[x,3] <- "2018"
dat[x,4] <- "Yes"
dat[x,5] <- "Majority subgroup-Continuting generation"
dat[x,6] <- "Course Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.47,2.63,1.21,1.14,438/2,438/4,dig = 5)[1,12:15]


# independent only
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1b)"
dat[x,3] <- "2018"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-First generation"
dat[x,6] <- "Course Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.18,1.25,0.74,1.24,438/4,438/4,dig = 5)[1,12:15]


x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Tibbetts (Study 1b)"
dat[x,3] <- "2018"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Continuting generation"
dat[x,6] <- "Course Grade"
dat[x,7] <- "No"
dat[x,8:11] <- mes(2.34,2.54,1.1,1.15,438/4,438/4,dig = 5)[1,12:15]

```

```{r Turetsky under review}
turetsky <- read.csv("Turetsky under review.csv", as.is = T)

# unadjusted

# CoursePointTotal
turetsky.s <- turetsky[turetsky$RaceMarg == "Marg",]
mt <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Course point total"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]


turetsky.s <- turetsky[turetsky$RaceMarg == "NonMarg",]
mt <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White and Asian"
dat[x,6] <- "Course point total"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]




turetsky.s <- turetsky[turetsky$Gender == "F",]
mt <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Course point total"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]


turetsky.s <- turetsky[turetsky$Gender == "M",]
mt <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$CoursePointTotal[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Course point total"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]


# TookSpringClass
turetsky.s <- turetsky[turetsky$RaceMarg == "Marg",]
mt <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Biology track persistence"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]


turetsky.s <- turetsky[turetsky$RaceMarg == "NonMarg",]
mt <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White and Asian"
dat[x,6] <- "Biology track persistence"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]



turetsky.s <- turetsky[turetsky$Gender == "F",]
mt <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Female"
dat[x,6] <- "Biology track persistence"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]


turetsky.s <- turetsky[turetsky$Gender == "M",]
mt <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
mc <- mean(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
sdt <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"], na.rm = T)
sdc <- sd(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"], na.rm = T)
nt <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "VAffirm"]))
nc <- length(!is.na(turetsky.s$TookSpringClass[turetsky.s$Intervention == "Control"]))

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Turetsky"
dat[x,3] <- "under review"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-Male"
dat[x,6] <- "Biology track persistence"
dat[x,7] <- "No"
dat[x,8:11] <- mes(mt,mc,sdt,sdc,nt,nc,dig = 5)[1,12:15]


#turetsky$RaceMargc <- ifelse(turetsky$RaceMarg == "Marg", 1,0)
#turetsky$Interventionc <- ifelse(turetsky$Intervention == "VAffirm", 0,1)
#
#turetsky$RaceMarg <- factor(turetsky$RaceMarg, levels = c("NonMarg","Marg"))
#fit1 <- lm(CoursePointTotal ~ RaceMargc * Interventionc, turetsky)
#fit2 <- lm(CoursePointTotal ~ Intervention, turetsky[turetsky$RaceMarg == #"Marg", ])
#fit3 <- lm(CoursePointTotal ~  Intervention, turetsky[turetsky$RaceMarg == #"NonMarg", ])
#
#coef(fit1)
#coef(fit2)
#coef(fit3)

```

```{r Woolf 2009}

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Woolf"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "Summative written essay score"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(0.063,0.244,0.9,1,79,84,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Woolf"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "Summative written essay score"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(-0.098,-0.175,1.09,0.96,95,77,dig = 5)[1,12:15]



x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Woolf"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Majority subgroup-White"
dat[x,6] <- "OSCE score"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(0.271,-0.002,0.96,0.96,79,84,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Woolf"
dat[x,3] <- "2009"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-URM"
dat[x,6] <- "OSCE score"
dat[x,7] <- "Yes"
dat[x,8:11] <- mes(0.001,-0.286,1,0.97,95,77,dig = 5)[1,12:15]

```

```{r Wynne 2011}

# GPA in History
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "Time 1 GPA in History"
dat[x,7] <- "No"
dat[x,8:11] <- mes(80.63,78.60,7.20,6.77,100/2,100/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black and Hispanic"
dat[x,6] <- "Time 2 GPA in History"
dat[x,7] <- "No"
dat[x,8:11] <- mes(79.43,78.40,9.23,7.16,100/2,100/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Time 1 GPA in History"
dat[x,7] <- "No"
dat[x,8:11] <- mes(80.23,78.39,6.91,6.46,71/2,71/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Time 2 GPA in History"
dat[x,7] <- "No"
dat[x,8:11] <- mes(78.89,78.39,8.66,7.21,71/2,71/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Time 1 GPA in History"
dat[x,7] <- "No"
dat[x,8:11] <- mes(81.69,79.06,8.11,7.61,29/2,29/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Time 2 GPA in History"
dat[x,7] <- "No"
dat[x,8:11] <- mes(80.92,78.44,10.87,7.28,29/2,29/2,dig = 5)[1,12:15]


# GPA overall

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Time 1 GPA Overall"
dat[x,7] <- "No"
dat[x,8:11] <- mes(79.81,78.09,7.17,6.52,100/2,100/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "Time 2 GPA in Overall"
dat[x,7] <- "No"
dat[x,8:11] <- mes(77.92,76.52,8.48,6.94,100/2,100/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Time 1 GPA in Overall"
dat[x,7] <- "No"
dat[x,8:11] <- mes(79.49,77.85,7.07,6.52,71/2,71/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "Time 2 GPA in Overall"
dat[x,7] <- "No"
dat[x,8:11] <- mes(77.53,76.08,8.53,7.24,71/2,71/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Time 1 GPA in Overall"
dat[x,7] <- "No"
dat[x,8:11] <- mes(80.66,78.64,7.65,6.68,29/2,29/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "Time 2 GPA in Overall"
dat[x,7] <- "No"
dat[x,8:11] <- mes(78.97,77.51,8.57,6.34,29/2,29/2,dig = 5)[1,12:15]

# MCAS ELA scores
x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "MCAS ELA scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(249.5,246.8,11.29,11.27,100/2,100/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "MCAS ELA scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(248.7,247.3,11.35,11.39,71/2,71/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "MCAS ELA scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(251.8,245.6,11.21,11.25,29/2,29/2,dig = 5)[1,12:15]

# MCAS Math scores

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Main"
dat[x,6] <- "MCAS Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(249.3,246.0,12.14,12.37,100/2,100/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Black"
dat[x,6] <- "MCAS Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(249.9,245.8,13.34,12.33,71/2,71/2,dig = 5)[1,12:15]

x<- nrow(dat[is.na(dat$author) == F,]) +1
dat[x,2] <- "Wynne"
dat[x,3] <- "2011"
dat[x,4] <- "No"
dat[x,5] <- "Minority subgroup-Hispanic"
dat[x,6] <- "MCAS Math scores"
dat[x,7] <- "No"
dat[x,8:11] <- mes(247.5,246.5,8.29,12.87,29/2,29/2,dig = 5)[1,12:15]
```

```{r data cleaning}

dat[is.na(dat$lowerCI) == T,"lowerCI"] <- dat[is.na(dat$lowerCI) == T,"es"] - 1.96 * sqrt(dat[is.na(dat$lowerCI) == T,"v"])

dat[is.na(dat$upperCI) == T,"upperCI"] <- dat[is.na(dat$upperCI) == T,"es"] + 1.96 * sqrt(dat[is.na(dat$upperCI) == T,"v"])

dat$se <- sqrt(dat$v)

dat[,c(8:12)]<- round(select(dat, es:se), 4)


#dat$study <- dat %>% group_indices(paste(author,year))

dat$study <- paste(dat$author, dat$year, sep = ", ")


#write.csv(dat, "all.csv", row.names = F)
```

```{r create clusters}

dat$temp <- paste(dat$author, dat$year, sep = " ")
dat$cluster <- dat$study

dat$cluster[dat$temp %in% c(
  "Borman 2015",
  "Borman 2016", 
  "Borman 2018", 
  "Hanselman 2014",
  "Hanselman (Study 1) 2017",
  "Hanselman (Study 2) 2017",
  "Rozek 2015")] <- "MWAP"

dat$cluster[dat$temp %in% c(
  "Harackiewicz 2014", 
  "Tibbetts (Study 1a) 2016")] <- "Harackiewicz et al."

dat$cluster[dat$temp %in% c(
  "Cohen (Study 1) 2006",
  "Cohen (Study 2) 2006",
  "Cohen 2009", 
  "Cook (Study 1) 2012",
  "Goyer (Study 2) 2017",
  "Powers (Study 1) 2016",
  "Powers (Study 2) 2016",
  "Shnabel (Study 1) 2013")] <- "Cohen et al."

dat$cluster[dat$temp %in% c(
  "Goyer (Study 1) 2017",
  "Sherman (Study 1) 2013")] <- "Sherman et al."

dat$cluster[dat$temp %in% c(
  "Serra-Garcia (Study 1) under review",
  "Miyake 2010",
  "Kost-Smith 2010",
  "Kost-Smith 2012")] <- "Miyake et al."

dat$cluster[dat$temp %in% c(
  "Bratter 2016", 
  "Bancroft 2017")] <- "Bratter et al."


dat$type_s <- gsub("(.*)(-)(.*)", "\\1",dat$type)
dat$group <- gsub("(.*)(-)(.*)", "\\3",dat$type)

dat$group_s[dat$group %in% c("Black", "Hispanic", "Asian","URM", "White", "Black and Hispanic", "Turkish", "Arabic", "Eastern European", "White and Asian", "Black Caribbeans")] <- "Race"
dat$group_s[dat$group %in% c("First generation","Continuing generation")] <- "First generation status"
dat$group_s[dat$group %in% c("URM or First generation")] <- "Mixed"
dat$group_s[dat$group %in% c("FSM","nonFSM")] <- "FSM status"
dat$group_s[dat$group %in% c("Female","Male")] <- "Gender"
dat$group_s[dat$group %in% c("Blind")] <- "Disability"
dat$group_s[dat$group %in% c("Main")] <- "None"


dat <- select(dat, study, cluster, author, year, adapted, type_s, group, group_s,outcome, adjusted, es, v, se, lowerCI, upperCI)

#write.csv(dat, "master.csv",row.names = F)
```

# Main Analysis

```{r multilevel analysis all outcomes}
# Minority group

dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) %>% select(cluster,study, year, group, outcome,es,se,v)


full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_by cluster.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 

# by study
dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_by study.pdf', width = 10, height = 11) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


pdf(file='funnelplot_minority.pdf', width = 18, height = 10) 
par(mar = c(6, 6, 2, 2))
meta::funnel(model,xlab = "Hedge's g", ylab = "Reverse-scaled Standard Errors\n(Top = More Precision)",studlab = F, cex.lab = 1.2, font.lab = 2)

text(model$TE[!model$studlab %in% c("Harackiewicz, 2014",
                                    "Tibbetts (Study 1a), 2016",
                                    "Schwalbe, 2018",
                                    "Serra-Garcia (Study 1), under review",
                                    "Bayly, 2017",
                                    "Dee, 2015",
                                    "Hanselman (Study 2), 2017",
                                    "Borman, 2012",
                                    "Baker, 2019",
                                    "Hanselman (Study 1), 2017",
                                    "Cohen (Study 1), 2006",
                                    "Protzko, 2016",
                                    "Lokhande, 2019",
                                    "Kinias (Study 2), 2016")],
     model$seTE[!model$studlab %in% c("Harackiewicz, 2014",
                                    "Tibbetts (Study 1a), 2016",
                                    "Schwalbe, 2018",
                                    "Serra-Garcia (Study 1), under review",
                                    "Bayly, 2017",
                                    "Dee, 2015",
                                    "Hanselman (Study 2), 2017",
                                    "Borman, 2012",
                                    "Baker, 2019",
                                    "Hanselman (Study 1), 2017",
                                    "Cohen (Study 1), 2006",
                                    "Protzko, 2016",
                                    "Lokhande, 2019",
                                    "Kinias (Study 2), 2016")]+0.005,
     model$studlab[!model$studlab %in% c("Harackiewicz, 2014",
                                    "Tibbetts (Study 1a), 2016",
                                    "Schwalbe, 2018",
                                    "Serra-Garcia (Study 1), under review",
                                    "Bayly, 2017",
                                    "Dee, 2015",
                                    "Hanselman (Study 2), 2017",
                                    "Borman, 2012",
                                    "Baker, 2019",
                                    "Hanselman (Study 1), 2017",
                                    "Cohen (Study 1), 2006",
                                    "Protzko, 2016",
                                    "Lokhande, 2019",
                                    "Kinias (Study 2), 2016")],cex=.8)

text(model$TE[model$studlab %in% c("Harackiewicz, 2014")]+0.065,
     model$seTE[model$studlab %in% c("Harackiewicz, 2014")],
     model$studlab[model$studlab %in% c("Harackiewicz, 2014")],cex=.8)

text(model$TE[model$studlab %in% c("Tibbetts (Study 1a), 2016")]-0.085,
     model$seTE[model$studlab %in% c("Tibbetts (Study 1a), 2016")],
     model$studlab[model$studlab %in% c("Tibbetts (Study 1a), 2016")],cex=.8)

text(model$TE[model$studlab %in% c("Schwalbe, 2018")]+0.055,
     model$seTE[model$studlab %in% c("Schwalbe, 2018")],
     model$studlab[model$studlab %in% c("Schwalbe, 2018")],cex=.8)

text(model$TE[model$studlab %in% c("Serra-Garcia (Study 1), under review")],
     model$seTE[model$studlab %in% c("Serra-Garcia (Study 1), under review")]-0.01,
     model$studlab[model$studlab %in% c("Serra-Garcia (Study 1), under review")],cex=.8)

text(model$TE[model$studlab %in% c("Bayly, 2017")]-0.041,
     model$seTE[model$studlab %in% c("Bayly, 2017")],
     model$studlab[model$studlab %in% c("Bayly, 2017")],cex=.8)

text(model$TE[model$studlab %in% c("Dee, 2015")],
     model$seTE[model$studlab %in% c("Dee, 2015")]-0.006,
     model$studlab[model$studlab %in% c("Dee, 2015")],cex=.8)

text(model$TE[model$studlab %in% c("Hanselman (Study 2), 2017")]-0.088,
     model$seTE[model$studlab %in% c("Hanselman (Study 2), 2017")],
     model$studlab[model$studlab %in% c("Hanselman (Study 2), 2017")],cex=.8)

text(model$TE[model$studlab %in% c("Borman, 2012")],
     model$seTE[model$studlab %in% c("Borman, 2012")]-0.006,
     model$studlab[model$studlab %in% c("Borman, 2012")],cex=.8)

text(model$TE[model$studlab %in% c("Baker, 2019")]+0.042,
     model$seTE[model$studlab %in% c("Baker, 2019")],
     model$studlab[model$studlab %in% c("Baker, 2019")],cex=.8)

text(model$TE[model$studlab %in% c("Hanselman (Study 1), 2017")]-0.095,
     model$seTE[model$studlab %in% c("Hanselman (Study 1), 2017")],
     model$studlab[model$studlab %in% c("Hanselman (Study 1), 2017")],cex=.8)

text(model$TE[model$studlab %in% c("Cohen (Study 1), 2006")]-0.075,
     model$seTE[model$studlab %in% c("Cohen (Study 1), 2006")],
     model$studlab[model$studlab %in% c("Cohen (Study 1), 2006")],cex=.8)

text(model$TE[model$studlab %in% c("Protzko, 2016")]+0.05,
     model$seTE[model$studlab %in% c("Protzko, 2016")],
     model$studlab[model$studlab %in% c("Protzko, 2016")],cex=.8)

text(model$TE[model$studlab %in% c("Lokhande, 2019")]+0.055,
     model$seTE[model$studlab %in% c("Lokhande, 2019")],
     model$studlab[model$studlab %in% c("Lokhande, 2019")],cex=.8)

text(model$TE[model$studlab %in% c("Kinias (Study 2), 2016")]+0.073,
     model$seTE[model$studlab %in% c("Kinias (Study 2), 2016")],
     model$studlab[model$studlab %in% c("Kinias (Study 2), 2016")],cex=.8)

dev.off() 


source("pcurve.R")
pdf(file='pcurve_minority.pdf', width = 8, height = 6) 
pcurve(model)

dev.off() 


eggers.test<-function(data){

  data<-data
  eggers<-meta::metabias(data)
  intercept<-as.numeric(eggers$estimate[1])
  intercept<-round(intercept,digits=3)
  se.intercept<-eggers$estimate[2]
  lower.intercept<-as.numeric(intercept-1.96*se.intercept)
  lower.intercept<-round(lower.intercept,digits = 2)
  higher.intercept<-as.numeric(intercept+1.96*se.intercept)
  higher.intercept<-round(higher.intercept,digits = 2)
  ci.intercept<-paste(lower.intercept,"-",higher.intercept)
  ci.intercept<-gsub(" ", "", ci.intercept, fixed = TRUE)
  intercept.pval<-as.numeric(eggers$p.value)
  intercept.pval<-round(intercept.pval,digits=5)
  eggers.output<-data.frame(intercept,ci.intercept, intercept.pval)
  names(eggers.output)<-c("intercept","95%CI","p-value")
  title<-"Results of Egger's test of the intercept"
  
print(title)
print(eggers.output)
}

eggers.test(data = model)


dat.s.pool <- dat.s %>% group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se),
                                                        v = mean(v))

metafor::fsn(yi = es, 
             sei = se, 
             data = dat.s.pool)

metafor::fsn(yi = es, 
             sei = se, 
             data = dat.s.pool, type = "Orwin")

metafor::fsn(yi = es, 
             vi = se, 
             data = dat.s, target = 0.01, type = "Orwin")

# Begg and Mazumdar’s rank correlation test
metafor::ranktest(dat.s.pool$es, 
                  dat.s.pool$v)

# majority group

dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Majority subgroup", "Interaction")) %>% filter(group %in% c("Male", "Asian","White", "nonFSM", "Continuing generation", "White and Asian")) %>% select(cluster,study, year, group, outcome,es,se,v)



full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)

# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))


model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_by cluster.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


# by study
dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_by study.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 

pdf(file='funnelplot_majority.pdf', width = 6, height = 4) 
meta::funnel(model,xlab = "Hedge's g", studlab = F)

dev.off() 

```

```{r multilevel analysis all GPA}
# Minority group
dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[grep("GPA",dat.s$outcome),]



full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_minority_unadjusted_by_cluster_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_unadjusted_by_study_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 



# majority group

dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Majority subgroup", "Interaction")) %>% filter(group %in% c("Male", "Asian","White", "nonFSM", "Continuing generation", "White and Asian")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[grep("GPA",dat.s$outcome),]


full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_unadjusted_by_cluster_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_majority_unadjusted_by_study_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 

```

```{r multilevel analysis all secondary}

# Minority group
dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[-grep("GPA",dat.s$outcome),]



full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_minority_unadjusted_by_cluster_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_unadjusted_by_study_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 



# majority group

dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Majority subgroup", "Interaction")) %>% filter(group %in% c("Male", "Asian","White", "nonFSM", "Continuing generation", "White and Asian")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[-grep("GPA",dat.s$outcome),]


full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(~ 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_unadjusted_by_cluster_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_majority_unadjusted_by_study_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 
```

```{r multilevel analysis adjusted outcomes}
# Minority group

dat.s <- dat[dat$adjusted == "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) %>% select(cluster,study, year, group, outcome,es,se,v)


full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_minority_adjusted_by_cluster.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>%
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_adjusted_by_study.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 



# majority group

dat.s <- dat[dat$adjusted == "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Majority subgroup", "Interaction")) %>% filter(group %in% c("Male","Asian","White", "nonFSM", "Continuing generation", "White and Asian")) %>% select(cluster,study, year, group, outcome,es,se,v)

full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)



# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_adjusted_by_cluster.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_majority_adjusted_by_study.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


```

```{r multilevel analysis adjusted GPA}
# Minority group
dat.s <- dat[dat$adjusted %in% "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[grep("GPA",dat.s$outcome),]



full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_minority_adjusted_by_cluster_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_adjusted_by_study_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 



# majority group

dat.s <- dat[dat$adjusted == "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Majority subgroup", "Interaction")) %>% filter(group %in% c("Male", "Asian","White", "nonFSM", "Continuing generation", "White and Asian")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[grep("GPA",dat.s$outcome),]


full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_adjusted_by_cluster_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_majority_adjusted_by_study_GPA.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 

```

```{r multilevel analysis adjusted secondary}

# Minority group
dat.s <- dat[dat$adjusted %in% "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[-grep("GPA",dat.s$outcome),]



full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_minority_adjusted_by_cluster_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_minority_adjusted_by_study_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 



# majority group

dat.s <- dat[dat$adjusted == "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Majority subgroup", "Interaction")) %>% filter(group %in% c("Male", "Asian","White", "nonFSM", "Continuing generation", "White and Asian")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s <- dat.s[-grep("GPA",dat.s$outcome),]


full.model<-metafor::rma.mv(es, 
                   v, 
                   random = list(~ 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML")

summary(full.model)


# by cluster
dat.s.pool <- dat.s %>% group_by(cluster) %>% summarise(es = mean(es),
                                                        se = mean(se))

model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(cluster),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model

pdf(file='forestplot_majority_adjusted_by_cluster_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Project cluster", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 


dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_majority_adjusted_by_study_other.pdf', width = 10, height = 8) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 
```

```{r main effect}
dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Main"),
                          study %in% c("Churchill, 2018", "De Clercq, 2019", "Lauer, 2013", "Peters, 2017", "Rapa, 2016"))  %>% select(cluster,study, year, group, outcome,es,se,v) 


# by study (only makes sense to look at average effect with 5 studies)
dat.s.pool <- dat.s %>% 
  group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))
model <- meta::metagen(es,
        se,
        data=dat.s.pool,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model


pdf(file='forestplot_main_by study.pdf', width = 10, height = 11) 
meta::forest(model,
             leftlabs = c("Study", "TE","seTE"),
             rightlabs = c("g","95% CI","weight"),
             text.random = "Overall effect",
            print.tau2 = FALSE,
             smlab = "")
dev.off() 
```

# Subgroup Analysis

```{r try}
dat.s <- dat

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White")) %>% select(cluster,study, year, group, outcome,es,se,v)

dat.s.pool <- dat.s %>% group_by(study) %>% summarise(es = mean(es),
                                                        se = mean(se))

dat.mod <- read.csv("extraction_basic.csv", as.is = T)

dat.mod <- select(dat.mod, author, year, samplesize, setting_type,identity_type, density_female:n_domains, duration_rough_month, number_rough, Appropriate_reading_level:Reinforcement)

dat.mod$study <- paste(dat.mod$author, dat.mod$year, sep = ", ")



dat.s <- left_join(dat.s.pool, select(dat.mod, study, author, year, samplesize, setting_type,identity_type, density_female:n_domains, duration_rough_month, number_rough, Appropriate_reading_level:Reinforcement), by = c("study"))




model <- meta::metagen(es,
        se,
        data=dat.s,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model






dat.n <- na.omit(select(dat.s, study, es, se, Ordinary))
model <- meta::metagen(es,
        se,
        data=dat.n,
        studlab=paste(study),
        comb.fixed = FALSE,
        comb.random = TRUE,
        method.tau = "SJ",
        hakn = TRUE,
        prediction=TRUE,
        sm="g")
model
meta::update.meta(model, 
                             byvar=dat.n$Ordinary, 
                             comb.random = TRUE, 
                             comb.fixed = FALSE)


meta::update.meta(model, 
                             byvar=dat.s$Early, 
                             comb.random = TRUE, 
                             comb.fixed = FALSE)




dat.mod$temp <- paste(dat.mod$author, dat.mod$year, sep = " ")
dat.mod$cluster <- dat.mod$temp

dat.mod$cluster[dat.mod$temp %in% c(
  "Borman 2015",
  "Borman 2016", 
  "Borman 2018", 
  "Hanselman 2014",
  "Hanselman (Study 1) 2017",
  "Hanselman (Study 2) 2017",
  "Rozek 2015")] <- "MWAP"

dat.mod$cluster[dat.mod$temp %in% c(
  "Harackiewicz 2014", 
  "Tibbetts (Study 1a) 2016")] <- "Harackiewicz et al."

dat.mod$cluster[dat.mod$temp %in% c(
  "Cohen (Study 1) 2006",
  "Cohen (Study 2) 2006",
  "Cohen 2009", 
  "Cook (Study 1) 2012",
  "Goyer (Study 2) 2017",
  "Powers (Study 1) 2016",
  "Powers (Study 2) 2016",
  "Shnabel (Study 1) 2013")] <- "Cohen et al."

dat.mod$cluster[dat.mod$temp %in% c(
  "Goyer (Study 1) 2017",
  "Sherman (Study 1) 2013")] <- "Sherman et al."

dat.mod$cluster[dat.mod$temp %in% c(
  "Serra-Garcia (Study 1) under review",
  "Miyake 2010",
  "Kost-Smith 2010",
  "Kost-Smith 2012")] <- "Miyake et al."

dat.mod$cluster[dat.mod$temp %in% c(
  "Bratter 2016", 
  "Bancroft 2017")] <- "Bratter et al."


dat.mod$duration_rough_month_c <- scale(dat.mod$duration_rough_month)

dat.mod$density_freelunch_c <- scale(1- dat.mod$density_freelunch)

#dat.s$samplesize_c <- -scale(dat.s$samplesize)

dat.mod$Good_for_you_c <- binary_scale(1-dat.mod$Good_for_you)

dat.mod$Ordinary_c <- binary_scale(dat.mod$Ordinary)

dat.mod.s <- dat.mod %>% group_by(cluster) %>% summarise(
  duration_rough_month = mean(duration_rough_month,na.rm = T),
    density_freelunch = mean(density_freelunch,na.rm = T),
  Good_for_you = mean(Good_for_you,na.rm = T),
  Ordinary = mean(Ordinary,na.rm = T)

)

dat.s <- dat %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) 
dat.s <- left_join(dat.s, select(dat.mod.s, cluster,duration_rough_month,density_freelunch,Good_for_you,Ordinary), by = c("cluster"))


model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                  ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  duration_rough_month)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                  ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ density_freelunch)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                  ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Ordinary)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                  ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Good_for_you)
summary(model.mods, digits = 5)






```

```{r descriptives of moderators}
# Moderators: 
# paper_type, n_school, samplesize, setting_type, identity_type, density_female, density_urm, density_firstgen, density_freelunch, n_domains, duration_rough, number_rough, control_type, affirm_type, adaptation, reinforcement, appropriate_reading_level, privacy, ungraded, ordinary, known_teacher, delivered_in_classroom, good_for_you, early, before_stress, random_sequence_generation, allocation_concealment, blinding_of_participants_and_personnel, blinding_of_outcome_assessment, incomplete_outcome_data, selective_reporting, other_sources_of_bias

# Implementation fidelity:
#  affirm_type, control_type, adaptation, reinforcement
# appropriate_reading_level, privacy, ungraded, ordinary, known_teacher, delivered_in_classroom, good_for_you, early, before_stress, n_domains, duration_rough, number_rough

# Contextual factors and study characteristics:
# paper_type, n_school, samplesize, setting_type, identity_type, density_female, density_urm, density_firstgen, density_freelunch, duration_rough, number_rough

# Risk of bias
# random_sequence_generation, allocation_concealment, blinding_of_participants_and_personnel, blinding_of_outcome_assessment, incomplete_outcome_data, selective_reporting, other_sources_of_bias



# Minority 
dat.mod <- read.csv("extraction_basic_revised.csv", as.is = T)

dat.mod <- janitor::clean_names(dat.mod)

dat.s <- left_join(dat, dat.mod, by = c("author", "year"))

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) 

dat.s$timing[dat.s$early == 1 & dat.s$before_stress == 0] <-  "early"
dat.s$timing[dat.s$early == 0 & dat.s$before_stress == 1] <-  "before_stress"
dat.s$timing[dat.s$early == 1 & dat.s$before_stress == 1] <-  "both"
dat.s$timing[dat.s$early == 0 & dat.s$before_stress == 0] <-  "neither"

table(dat.s$timing)
```

```{r subgroup analysis all outcomes multilevel}

# function to run moderator analysis

get.mod <- function(mod){
  
  if(is.numeric(dat.s[,mod]) == T){
  model.mods <- rma.mv(es, 
                   v, 
                   random = list( ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ eval(as.name(mod))) # specify a moderator
  } else {
  model.mods <- rma.mv(es, 
                   v, 
                   random = list( ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ eval(as.name(mod))- 1)  # specify a moderator
  }
   
df <- data.frame(coef = gsub("^eval\\(as\\.name\\(mod\\)\\)", paste(mod,"_" ,sep = ""),rownames(model.mods$b)),
           estimate = model.mods$b[,1],
           se = model.mods$se, 
           tval = model.mods$zval, # I specified tdist = T
           pval = model.mods$pval,
           ci.lb =  model.mods$ci.lb,
           ci.ub =  model.mods$ci.ub
           )

df[,-1] <- round(df[,-1], digits = 5)
rownames(df) <- NULL
  
  return(df)
}

mod.list <- c("paper_type", "n_school", "samplesize", "setting_type", "identity_type", "density_female", "density_urm", "density_firstgen", "density_freelunch", "n_domains", "duration_rough_month", "number_rough", "control_type", "affirm_type", "adaptation", "reinforcement", "appropriate_reading_level", "privacy", "ungraded", "ordinary", "known_teacher", "delivered_in_classroom", "good_for_you", "early", "before_stress", "timing","random_sequence_generation", "allocation_concealment", "blinding_of_participants_and_personnel", "blinding_of_outcome_assessment", "incomplete_outcome_data", "selective_reporting", "other_sources_of_bias")

mod.results <- data.frame(
  coef = NA,
  estimate = NA,
  se = NA,
  tval = NA,
  pval = NA,
  ci.lb = NA,
  ci.ub = NA
)

for (i in 1:length(mod.list)) {
  
  mod.results <- rbind(mod.results, get.mod(mod.list[i]))
  
}


mod.results1 <- mod.results
mod.results2 <- mod.results

get.mod("ungraded")
temp <- sapply(dat.mod, table)


model.mods<-rma.mv(es, 
                   v, 
                   random = list( ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s[dat.s$setting_type %in% c("middle school", "high school", "primary school"),],
                   method = "REML",
                   mods = ~ ungraded)
summary(model.mods, digits = 5)


## Study characteristics

# samplesize (-*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ samplesize)
summary(model.mods, digits = 5)

# setting_type (middle, university+*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster/study), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ setting_type-1)
summary(model.mods)


# group_s (+* race FSM(marginal))
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster/study), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  group_s -1)
summary(model.mods)


# density_female
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster/study), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ density_female)
summary(model.mods)


# density_URM
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster/study), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ density_urm)
summary(model.mods)


# density_firstgen
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster/study), 
                   tdist = TRUE, 
                   data = dat.s[dat.s$setting_type == "university",],
                   method = "REML",
                   mods = ~ density_firstgen)
summary(model.mods)


# density_freelunch (-*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster/study), 
                   tdist = TRUE, 
                   data = dat.s[dat.s$setting_type != "university",],
                   method = "REML",
                   mods = ~ density_freelunch)
summary(model.mods)





# intervention characteristics

# n_domains
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ n_domains)
summary(model.mods)
 

# duration_rough_month (+*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ duration_rough_month)
summary(model.mods)


# number_rough ()
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ number_rough)
summary(model.mods)



# Ungraded
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Ungraded)
summary(model.mods)


# Known_teacher
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Known_teacher)
summary(model.mods)


# Delivered_in_classroom
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Delivered_in_classroom)
summary(model.mods)



# Good_for_you
model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Good_for_you)
summary(model.mods)

# Ordinary ( +*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Ordinary)
summary(model.mods)

# Early 
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Early)
summary(model.mods)


# Timely
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Timely)
summary(model.mods)

dat.s$timing[dat.s$Early == 1 & dat.s$Timely == 0] <-  "Early"
dat.s$timing[dat.s$Early == 0 & dat.s$Timely == 1] <-  "Timely"
dat.s$timing[dat.s$Early == 1 & dat.s$Timely == 1] <-  "Both"
dat.s$timing[dat.s$Early == 0 & dat.s$Timely == 0] <-  "None"

table(dat.s$timing)

dat.s$timing <- factor(dat.s$timing, levels = c("Timely", "Early", "Both", "None"))
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ timing-1)
summary(model.mods)

# Reinforcement
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Reinforcement)
summary(model.mods)

model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ adapted)
summary(model.mods)


# fidelity index
dat.s$fidelity <- rowSums(dat.s[,26:33], na.rm = T)
summary(dat.s$fidelity)

model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ fidelity)
summary(model.mods)

```

```{r subgroup analysis all adjusted outcomes multilevel}

# Minority 

# Minority 
dat.mod <- read.csv("extraction_basic.csv", as.is = T)

dat.s <- left_join(dat, select(dat.mod, author, year, samplesize, setting_type,identity_type, density_female:n_domains, duration_rough_month, number_rough, Ungraded:Reinforcement), by = c("author", "year"))


dat.s <- dat.s[dat.s$adjusted == "Yes",]

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) 




## Study characteristics

# samplesize (-*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ samplesize)
summary(model.mods)

# setting_type (middle, university+*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ setting_type-1)
summary(model.mods)


# group_s (+* gender(marginal) race FSM)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  group_s -1)
summary(model.mods)


# density_female
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ density_female)
summary(model.mods)


# density_URM
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s[dat.s$group_s %in% "Race",],
                   method = "REML",
                   mods = ~ density_URM)
summary(model.mods)


# density_firstgen (-*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s[dat.s$setting_type == "university",],
                   method = "REML",
                   mods = ~ density_firstgen)
summary(model.mods)


# density_freelunch (-*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s[dat.s$setting_type != "university",],
                   method = "REML",
                   mods = ~ density_freelunch)
summary(model.mods)





# intervention characteristics

# n_domains
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ n_domains)
summary(model.mods)


# duration_rough_month (+*)
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ duration_rough_month)
summary(model.mods)


# number_rough 
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ number_rough)
summary(model.mods)



# Ungraded
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Ungraded)
summary(model.mods)



# Known_teacher
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Known_teacher)
summary(model.mods)


# Delivered_in_classroom
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Delivered_in_classroom)
summary(model.mods)




# Good_for_you
model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Good_for_you)
summary(model.mods)

# Ordinary
model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Ordinary)
summary(model.mods)

# Early
model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Early)
summary(model.mods)


# Timely
model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Timely)
summary(model.mods)

# Reinforcement (+)
model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ Reinforcement)
summary(model.mods)

model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ adapted)
summary(model.mods)


# fidelity index
dat.s$fidelity <- rowSums(dat.s[,26:38], na.rm = T)
summary(dat.s$fidelity)

model.mods<-rma.mv(es, 
                   v, 
                   random = list( 
                                 ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~ fidelity)
summary(model.mods)

```

```{r meta regression}

# subgroup analysis all outcomes

# Minority 
dat.mod <- read.csv("extraction_basic.csv", as.is = T)

dat.s <- left_join(dat, select(dat.mod, author, year, samplesize, setting_type,identity_type, density_female:n_domains, duration_rough_month, number_rough, Ungraded:Reinforcement), by = c("author", "year"))

dat.s <- dat.s %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) 


x <- as.data.frame(cor(dat.s[,c(16,22,24:38)], use = "complete.obs"))



model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s %>% filter(samplesize >= 
                                             summary(samplesize)[5]),
                   method = "REML")
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s %>% filter(samplesize <= 
                                             summary(samplesize)[2]),
                   method = "REML")
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_freelunch * Early)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_freelunch * Early)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_URM * Early)
summary(model.mods, digits = 5)



model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  duration_rough_month + density_freelunch+ Ordinary)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  duration_rough_month + Ordinary)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_freelunch * duration_rough_month)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_freelunch * Ordinary)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  duration_rough_month * Ordinary)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  samplesize + number_rough)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  number_rough + duration_rough_month)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  samplesize + duration_rough_month + number_rough + Early)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_freelunch )
summary(model.mods, digits = 5)



dat.n <- dat.s %>% group_by(study) %>% summarise(
  samplesize = mean(samplesize, na.rm = T),
  density_freelunch = mean(density_freelunch, na.rm = T),
    number_rough = mean(number_rough, na.rm = T),
  duration_rough_month = mean(duration_rough_month, na.rm = T),
  Reinforcement = mean(Reinforcement, na.rm = T)
)
  
Hmisc::rcorr(as.matrix(dat.n[,c("samplesize", "duration_rough_month", "number_rough", "Reinforcement","density_freelunch")]))


binary_scale <- function(var){
  return(
    (var-mean(var,na.rm = T))/(2*sd(var,na.rm = T)^2)
  )
  
}



dat.mod$duration_rough_month_c <- scale(dat.mod$duration_rough_month)

dat.mod$density_freelunch_c <- scale(1- dat.mod$density_freelunch)

dat.mod$timing <- NA
dat.mod$timing[dat.mod$Early == 1 & dat.mod$Timely == 0] <-  2
dat.mod$timing[dat.mod$Early == 0 & dat.mod$Timely == 1] <-  1
dat.mod$timing[dat.mod$Early == 1 & dat.mod$Timely == 1] <-  3
dat.mod$timing[dat.mod$Early == 0 & dat.mod$Timely == 0] <-  0

dat.mod$timing_c <- scale(dat.mod$timing)

#dat.s$samplesize_c <- -scale(dat.s$samplesize)

dat.mod$Ungraded_c <- binary_scale(dat.mod$Ungraded)
dat.mod$Ordinary_c <- binary_scale(dat.mod$Ordinary)
dat.mod$Known_teacher_c <- binary_scale(dat.mod$Known_teacher)
dat.mod$Delivered_in_classroom_c <- binary_scale(dat.mod$Delivered_in_classroom)
dat.mod$Non_Good_for_you_c <- binary_scale(1-dat.mod$Good_for_you)
dat.mod$Timely_c <- binary_scale(dat.mod$Timely)

dat.mod$fidelity_implementation <- rowSums(dat.mod[,c("duration_rough_month_c","Ordinary_c", "timing_c")], na.rm = T)
dat.mod$fidelity_implementation <- scale(dat.mod$fidelity_implementation)
dat.mod$fidelity_implementation_c <- cut(dat.mod$fidelity_implementation, 2)
dat.mod$fidelity_implementation_c3 <- cut(dat.mod$fidelity_implementation, 3)


dat.mod$fidelity_contextual <- dat.mod[,c("density_freelunch_c")]
dat.mod$fidelity_contextual <- scale(dat.mod$fidelity_contextual)
dat.mod$fidelity_contextual_c <- cut(dat.mod$fidelity_contextual, 2)
dat.mod$fidelity_contextual_c3 <- cut(dat.mod$fidelity_contextual, 3)

dat.mod$fidelity_everything <- rowSums(select(dat.mod, duration_rough_month_c:Timely_c), na.rm = T)
dat.mod$fidelity_everything <- scale(dat.mod$fidelity_everything)
dat.mod$fidelity_everything_c <- cut(dat.mod$fidelity_everything, 2)
dat.mod$fidelity_everything_c3 <- cut(dat.mod$fidelity_everything, 3)




dat.s <- dat %>% filter(type_s %in% c("Minority subgroup", "Interaction")) %>% filter(!group %in% c("White", "Asian","Male","White and Asian", "Continuing generation")) 
dat.s <- left_join(dat.s, select(dat.mod, author, year,duration_rough_month_c,density_freelunch_c,Ungraded_c,Ordinary_c,Known_teacher_c,Delivered_in_classroom_c,Non_Good_for_you_c,Timely_c,fidelity_implementation,fidelity_implementation_c,fidelity_implementation_c3,fidelity_contextual,fidelity_contextual_c,fidelity_contextual_c3,fidelity_everything,fidelity_everything_c, fidelity_everything_c3, timing_c), by = c("author", "year"))


model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                  ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  timing_c)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                  ~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  duration_rough_month_c)
summary(model.mods, digits = 5)




model.mods<-rma.mv(es, 
                   v, 
                   random = list(
                                   ~1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  density_freelunch_c)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  Ordinary_c)
summary(model.mods, digits = 5)


Hmisc::rcorr(as.matrix(dat.mod[,40:42]))



implementation <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation)
summary(implementation, digits = 5)

implementation_c2 <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_c-1)
summary(model.mods, digits = 5)

implementation_c3 <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_c3 -1)
summary(model.mods, digits = 5)



contextual <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_contextual)
summary(contextual, digits = 5)


contextual_c2 <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_contextual_c -1)
summary(model.mods, digits = 5)

contextual_c3 <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_contextual_c3 -1)
summary(model.mods, digits = 5)

dat.s$fidelity_all <- rowSums(dat.s[,c("fidelity_implementation", "fidelity_contextual")], na.rm = T)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_all)
summary(model.mods, digits = 5)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation * fidelity_contextual)
summary(model.mods, digits = 5)


dat.s$fidelity_implementation_p1sd <- dat.s$fidelity_implementation + sd(dat.s$fidelity_implementation,na.rm = T)

dat.s$fidelity_implementation_m1sd <- dat.s$fidelity_implementation - sd(dat.s$fidelity_implementation,na.rm = T)

dat.s$fidelity_contextual_p1sd <- dat.s$fidelity_contextual + sd(dat.s$fidelity_contextual,na.rm = T)

dat.s$fidelity_contextual_m1sd <- dat.s$fidelity_contextual - sd(dat.s$fidelity_contextual,na.rm = T)


model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_p1sd)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_m1sd)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_contextual_p1sd)
summary(model.mods, digits = 5)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_contextual_m1sd)
summary(model.mods, digits = 5)


m1<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation + fidelity_contextual)
summary(model.mods, digits = 5)

m2<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation + fidelity_contextual_p1sd)
summary(m2, digits = 5)

m3<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation + fidelity_contextual_m1sd)
summary(m3, digits = 5)

m4<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_p1sd + fidelity_contextual)
summary(m4, digits = 5)

m5<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_p1sd + fidelity_contextual_p1sd)
summary(m5, digits = 5)

m6<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_p1sd + fidelity_contextual_m1sd)
summary(model.mods, digits = 5)



m7<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_m1sd + fidelity_contextual)
summary(m7, digits = 5)


m8<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_m1sd + fidelity_contextual_p1sd)
summary(model.mods, digits = 5)

m9<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_implementation_m1sd + fidelity_contextual_m1sd)
summary(m9, digits = 5)

x <- rbind(
coef(summary(m1)),
coef(summary(m2)),
coef(summary(m3)),
coef(summary(m4)),
coef(summary(m5)),
coef(summary(m6)),
coef(summary(m7)),
coef(summary(m8)),
coef(summary(m9))
)

write.csv(x, "test2.csv")




model.mods <-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_everything)
summary(model.mods, digits = 5)



everything_c2<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_everything_c-1)
summary(model.mods, digits = 5)



everything_c3<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity_everything_c3-1)
summary(everything_c3, digits = 5)


xtable(coef(summary(implementation)))

x <- rbind(
coef(summary(implementation)),
coef(summary(implementation_c2)),
coef(summary(implementation_c3)),
coef(summary(contextual)),
coef(summary(contextual_c2)),
coef(summary(contextual_c3)),
coef(summary(everything_c)),
coef(summary(everything_c2)),
coef(summary(everything_c3))
)

write.csv(x, "test.csv")

dat.s$duration_rough_month_c <- ifelse(dat.s$duration_rough_month >=                                    summary(dat.s$duration_rough_month)[4],1,0)

dat.s$density_freelunch_c <- ifelse(dat.s$density_freelunch >= 
                                         summary(dat.s$density_freelunch)[4],0,1)


dat.s$Not_Good_for_you <- 1 - dat.s$Good_for_you

dat.s$fidelity2 <- rowSums(dat.s[,c(26:29,31:34,36,37)], na.rm = T)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity2)
summary(model.mods, digits = 5)



dat.s$fidelity3 <- rowSums(dat.s[,c(26:29,31:33,37)], na.rm = T)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity3)
summary(model.mods, digits = 5)


dat.s$fidelity4 <- rowSums(dat.s[,c(26,27,31,37)], na.rm = T)
dat.s$fidelity4 <- ifelse(dat.s$fidelity4 == 4, 1, 0)

model.mods<-rma.mv(es, 
                   v, 
                   random = list(~ 1 | cluster), 
                   tdist = TRUE, 
                   data = dat.s,
                   method = "REML",
                   mods = ~  fidelity4)
summary(model.mods, digits = 5)



unique(dat.s$study[dat.s$Ungraded == 0])
unique(dat.s$study[dat.s$Ungraded == 1])

unique(dat.s$study[dat.s$Known_teacher == 0])
unique(dat.s$study[dat.s$Known_teacher == 1])

unique(dat.s$study[dat.s$Ordinary == 0])
unique(dat.s$study[dat.s$Ordinary == 1])

unique(dat.s$study[dat.s$Delivered_in_classroom == 0])
unique(dat.s$study[dat.s$Delivered_in_classroom == 1])

unique(dat.s$study[dat.s$Good_for_you == 0])
unique(dat.s$study[dat.s$Good_for_you == 1])

unique(dat.s$study[dat.s$Early == 0])
unique(dat.s$study[dat.s$Early == 1])
```

```{r analysis basic info}
dat.mod <- read.csv("extraction_basic.csv", as.is = T)

unique(na.omit(dat)$study)
unique(na.omit(dat)$cluster)

View(t(sapply(select(dat.mod, Ungraded:Reinforcement), table)))
summary(dat.mod$duration_rough_month)
summary(dat.mod$number_rough)
summary(dat.mod$n_domains)

x <- as.data.frame(table(dat.mod$paper_type)); View(x)
x <- as.data.frame(table(dat.mod$setting_type)); View(x)
x <- as.data.frame(table(dat.mod$identity_type)); View(x)

dat.mod$year_c <- ifelse(dat.mod$year %in% c("2006", "2009", "2010", "2011"), "2006-2011", dat.mod$year)

dat.mod$year_c <- ifelse(dat.mod$year_c %in% c("2012", "2013", "2014", "2015"), "2012-2015", dat.mod$year_c)

dat.mod$year_c <- ifelse(dat.mod$year_c %in% c("2016", "2017", "2018", "2019"), "2016-2019", dat.mod$year_c)

x <- as.data.frame(table(dat.mod$year_c)); View(x)

# older codes (not used in paper)
dat.mod$year <- as.factor(dat.mod$year)

dat.mod$cluster <- dat.mod$author

dat.mod$cluster[dat.mod$cluster %in% c("Borman", "Hanselman","Hanselman (Study 1)","Hanselman (Study 2)", "Rozek")] <- "MMSD"
dat.mod$cluster[dat.mod$cluster %in% c("Harackiewicz", "Tibbetts")] <- "Harackiewicz & Tibbetts"
dat.mod$cluster[dat.mod$cluster %in% c("Cohen","Cohen (Study 1)","Cohen (Study 2)", "Shnabel (Study 1)")] <- "Cohen & Shnabel"

p1 <- ggplot(dat.mod, aes(year)) +
  geom_histogram(stat= "count", color = "black") + theme_bw() + labs(x = "\nYear", y = "Frequency\n") + 
  theme(text=element_text(size=16)) + scale_y_continuous(breaks = seq(0, 1, by = 2))

ggsave("Year.jpeg",p1, dpi = 600, height = 6, width = 12)

p2 <- boxplot(dat.mod$Sample.Size, ylab = "Sample Size")
stripchart(dat.mod$Sample.Size, vertical = TRUE, 
    method = "jitter", add = TRUE, pch = 20, col = 'blue')

points(x = 1, 
       y = mean(dat.mod$Sample.Size,na.rm = T), 
       pch = 19, 
       col = "red") # add points for the mean value

text(x = 1, 
     y = mean(dat.mod$Sample.Size,na.rm = T) + 60, 
     labels = paste("Mean = ", 
                    round(mean(dat.mod$Sample.Size,na.rm = T),1), 
                    sep = "") ) # add label for the mean value

text(x = 1, 
     y = mean(dat.mod$Sample.Size,na.rm = T) + 60, 
     labels = paste("Mean = ", 
                    round(mean(dat.mod$Sample.Size,na.rm = T),1), 
                    sep = "") )
text(x = 1.1,
     y = 2665,
     labels = "Dee, 2015")

text(x = 1.15,
     y = 1318,
     labels = "Borman et al., 2012")

text(x = 1.4, 
     y = p2$stats + c(10, 0,0,0, -10), 
     labels = paste(c("Minimum = ", 
                      "Lower Quartile = ", 
                      "Median = ", 
                      "Upper Quartile = ", 
                      "Maximum = "),
       round(p2$stats,1),
       sep = "")
     ) # add labels and value for the 5 summary statistics


dat.mod.s <- dat.mod %>% group_by(cluster) %>% summarise(Sample.Size = mean(Sample.Size))

mean(dat.mod$Sample.Size,na.rm = T)
sd(dat.mod$Sample.Size,na.rm = T)

mean(dat.mod.s$Sample.Size,na.rm = T)
sd(dat.mod.s$Sample.Size,na.rm = T)





dat.mod$Disadvantaged.Group <- as.factor(dat.mod$Disadvantaged.Group )


dat.mod <- dat.mod %>% mutate(Disadvantaged.Group = fct_relevel(Disadvantaged.Group, c("Black", "Hispanic","Black & Hispanic",  "Blacks, Hispanic, Native Americans, and Hawaiian and Pacific Islanders","Female" , "Female & Black" ,"First-generation students","Ethnic minority in Netherland","Ethnic minority in UK" ,"None" )))

levels(dat.mod$Disadvantaged.Group)[c(4,7,8,9)] <- c("Blacks,Hispanic,\nNative Americans,\nand Hawaiian and Pacific Islanders", "First-generation\nstudents", "Ethnic minority\nin Netherland", "Ethnic minority\nin UK")

p3 <-  ggplot(dat.mod, aes(Disadvantaged.Group)) +
  geom_histogram(stat= "count", color = "black") + theme_bw() + labs(x = "", y = "Frequency\n") + 
  theme(text=element_text(size=16)) + scale_y_continuous(breaks = seq(0, 10, by = 2))

ggsave("Disadvantaged.Group.jpeg",p3, dpi = 600, height = 8, width = 16)



dat.mod$Advantaged.Group <- as.factor(dat.mod$Advantaged.Group )

dat.mod <- dat.mod %>% mutate(Advantaged.Group = fct_relevel(Advantaged.Group,
                                                                  levels(dat.mod$Advantaged.Group)[c(9,1:8)]
                                                               
                                                               ))

levels(dat.mod$Advantaged.Group)[c(3:5)] <- c("Asian, White\n&Multiracial", "Asians, White,\nPacific Islanders,\nNative American and other", "Continuing-generation\nstudents")

p4 <- ggplot(dat.mod, aes(Advantaged.Group)) +
  geom_histogram(stat= "count", color = "black") + theme_bw() + labs(x = "", y = "Frequency\n") + 
  theme(text=element_text(size=16)) + scale_y_continuous(breaks = seq(0, 14, by = 2))

ggsave("Advantaged.Group.jpeg",p4, dpi = 600, height = 8, width = 16)


dat.mod$number <- as.factor(dat.mod$number)

p5 <- ggplot(dat.mod, aes(number)) +
  geom_histogram(stat= "count", color = "black") + theme_bw() + labs(x = "", y = "Frequency\n") + 
  theme(text=element_text(size=16)) + scale_y_continuous(breaks = seq(0, 14, by = 2))

ggsave("Number of intervention.jpeg",p5, dpi = 600, height = 8, width = 16)


sum(dat.mod$reinforcement)
sum(dat.mod$disguised, na.rm = T)

```


# Risk of bias assessment

```{r risk of bias}

dat.rob <- select(dat.mod, Random_sequence_generation : Other_sources_of_bias)

dat.rob <- dat.rob[,7:1]

rob.summary<-function(data){
    rob.vars<-data.frame(data)
    rob.vars$Author<-NULL
    ncol.rob.vars<-ncol(rob.vars)
    last<-colnames(rob.vars[ncol.rob.vars])
    first<-colnames(rob.vars[1])
    rob.long <- gather(data,
                   condition, measurement,
                   first:last,
                   factor_key=TRUE)
    rob.long$measurement<-as.factor(rob.long$measurement)
    rob.long$measurement<-factor(rob.long$measurement,
                             levels(rob.long$measurement)[c(1,3,2)])
    levels(rob.long$condition) <- c(
      "Other sources of bias"                 ,
      "Selective reporting"                   ,
      "Incomplete outcome data"               ,
      "Blinding of outcome assessment"        ,
      "Blinding of participants and personnel",
      "Allocation concealment"                ,
      "Random sequence generation" 
    )
    
    rob.plot<-ggplot(data=rob.long)+
      geom_bar(mapping=aes(x=condition,fill=measurement),
           width=0.7,
           position = "fill",
           color="black")+
      coord_flip(ylim = c(0,1))+
      guides(fill = guide_legend(reverse = TRUE))+
      scale_fill_manual("Risk of Bias",
                    labels = c("    High risk of bias          ",
                               "    Unclear risk of bias       ",
                               "    Low risk of bias  "),
                    values = c("unclear" = "#E2DF07",
                               "high" = "#BF0000",
                               "low" = "#02C100"))+
      scale_y_continuous(labels = scales::percent)+
      theme(axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y = element_text(size=18, color = "black"),
        axis.line.x = element_line(colour = "black",
                                   size = 0.5, linetype = "solid"),
        legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.background = element_rect(linetype="solid",
                                         colour ="black"),
        legend.title = element_blank(),
        legend.key.size = unit(0.75,"cm"),
        legend.text=element_text(size=14))
return(rob.plot)
}



pdf(file='revman.pdf', width = 16, height = 8) 
rob.summary(dat.rob)
dev.off() 


# traffic light plot
dat.mod$author_year <- paste(dat.mod$author, dat.mod$year, sep = ", ")
dat.rob2 <- select(dat.mod, author_year ,Random_sequence_generation : Other_sources_of_bias)

robvis::rob_traffic_light(data = dat.rob2, tool = "ROB2")



```

